[WF-654] Basic adoption tracker script
datacamp/waffles pull request #100
Opened 2022-09-28 15:23 UTC by blurbyte

# Basic adoption tracker script

## [WF-654](https://datacamp.atlassian.net/browse/WF-654)

## Changes

Implemented basic adoption tracker. Currently it shows all _datacamp-engineering_ repos which are using Waffles packages as dependency (Legacy, Old, New) with their versions. The data structure is following:
```
{
  repo_name1: {
    waffles_dependency1: [version],
    waffles_dependency2: [version1, version2] // monorepos can have multiple versions of same package
    ...
  },
  repo_name2: {
    waffles_dependency3: [version],
  },
  ...
}
```

TODO:

- track number of imports of various components in repos
- consume GITHUB_TOKEN from Circle CI

2022-11-30 15:09 UTC, ixTec requested changes
Overall looks great! Nice to start seeing some data around usage within projects!

Had a light read of the changes and got a few comments / questions about them so far, with more to come tomorrow I imagine:

- I think we may want to run the cron job after each release (not as part of release ,but after) as well (see comment in `docs/DEVELOPMENT.md`)
- Thought we wanted to avoid using `New/Old` terminology? 😄  I think using `Old` and `Current` / `Latest` would be better instead of `New`
- I like the use of a lighter/less prominent badge-type component for the component counts, but I think the version badges for old/new waffles variants should use `small` Waffles `Badge` for consistency with out components. The other ones can be replaced with the future `Tag` component.
    - Technically we say only text should be used in badges, but I think we can have the use case for it here, until `Tag` etc are available. This stops us having two variants of a custom component for now too

2022-11-30 15:09 UTC, ixTec commented on doc-site/components/adoption-global-usage.tsx
> +  margin-top: -${tokens.spacing.medium};
Is this negative margin necessary? Spacing won't match the other piecharts for the detailed views now

2022-11-30 15:09 UTC, ixTec commented on doc-site/components/adoption-dependencies.tsx
> +                    css={
I would move these styles out the return and instead call them from a `const` above. Starting to get a bit messy atm

2022-11-30 15:09 UTC, ixTec commented on doc-site/components/adoption-badge.tsx
> +    version === 'new' ? tokens.colors.green : tokens.colors.orange,
These feel like something we can put inside of a `map` and reference via e.g. `colorsMap[version].backgroundColor` etc

2022-11-30 15:18 UTC, blurbyte commented on docs/DEVELOPMENT.md
> +  - When changes hit `master` branch, before docs got deployed, most up to date `adoption-report.json` is copied from _Waffles S3 bucket_. This way there is no need to run adoption script on every re
No it is always up to date. For regular release current `adoption-report.json` is copied during docs pre-build step.

2022-11-30 15:24 UTC, blurbyte commented on doc-site/pages/overview/adoption.tsx
> +        <Notification
Initially I placed it at the top, but at the end not really sure if it matters that much, since it's taking some real estate, and ppl just want to see stats. 

We can wait and see, if ppl start complaining that data is inaccurate we can move it to the top :)

2022-11-30 15:25 UTC, blurbyte commented on doc-site/pages/overview/adoption.tsx
> +              New Waffles version is slightly outdated and should be upgraded
Could be confusing, since it only marks projects using New Waffles. We consider all Old Waffles outdated.

2022-11-30 15:27 UTC, blurbyte commented on doc-site/pages/overview/adoption.tsx
> +            <Text css={listDescriptionStyle}>Project is using New Waffles</Text>
Trying to use most common terminology in our org to avoid any confusion. Probably at some point we should make a push to call New Waffles just Waffles again, but I think right now it's a bit too early.

2022-11-30 15:35 UTC, blurbyte commented on doc-site/components/adoption-global.tsx
> +    project.components.new.forEach((component) => {
I understand it's not DRY but I tried to abstract it, and it was nearly impossible to understand when everything was put in some nested map + reduce. So I would keep it as it is for readability sake. Will add a comment to explain it a bit more.

2022-11-30 15:53 UTC, blurbyte commented
> Thought we wanted to avoid using New/Old terminology? 😄 I think using Old and Current / Latest would be better instead of New

Yes ideally, but currently these names are so widespread, so probably it's better to embrace it for now. By the end of neext quarter maybe we can start calling **New Waffles** just **Waffles**.

> The version badges for old/new waffles variants should use small Waffles Badge for consistency with out components.
The one in dependecies list in details with dependency name and version next to it, right?

I wouldn't worry too much about those Tags / Badges for now, just created something ad hoc which looked decent for this particular use case (started with our regular Badge but it was just too heavy).

2022-12-02 11:49 UTC, blurbyte commented on doc-site/components/adoption-global.tsx
> +    project.components.new.forEach((component) => {
Updated it slightly. It's quite tricky since it needs access to all projects and go through old / new components for each of these projects.

2022-12-02 11:56 UTC, blurbyte commented on doc-site/components/adoption-dependencies.tsx
> +                    css={
It's just 1 line of CSS technically.

2022-12-02 11:59 UTC, blurbyte commented on doc-site/components/adoption-global-usage.tsx
> +  margin-top: -${tokens.spacing.medium};
It just looks nicer, as there is no control of this pie chart wrapper (and default spacing is quite big since it assumes there will be labels too). For other diagrams it's not that problematic since list of components to the right is often taller then chart itself.

2022-12-02 12:02 UTC, blurbyte commented on doc-site/pages/overview/adoption.tsx
> +      description="Tracking adoption of New Waffles across all DataCamp projects, with detailed dependencies and components usage statistics for both New and Old Waffles."
It's quite tricky, because there are a lot of vars and some custom styles defined here. Would require to build yet another layer of components just to place them in MDX. Not sure if it's worth the hassle just to have content ToC.

2022-12-02 12:13 UTC, blurbyte commented
Overview of implemented changes:
- Updated Adoption page so New Waffles is now referred to as just Waffles.
- Refactor transform func in `AdoptionGlobal` to be DRYer.
- Described better what is Waffles / Old Waffles in Legend.
- I would still keep New / Old terminology internally for this particular case. I feel it's a bit more cleared than Latest / Current, which kind of implies the latest New Waffles version, instead just separate package.
- For version badges I tried our `Badge` but it made the whole page really hard to read, as they draw so much attention.

2022-12-06 11:06 UTC, ixTec requested changes

2022-12-06 11:06 UTC, ixTec commented on doc-site/pages/overview/adoption.tsx
> +        <Notification
I think it's better to place at the top still, just as a small disclaimer. We can probably simplify text even more also

2022-12-06 11:06 UTC, ixTec commented on doc-site/pages/overview/adoption.tsx
> +        <Notification
Perhaps "As our tracker uses the GitHub search API to gather data from all DataCamp repositories, it may hold incomplete information due to the limitations of this API. Nevertheless, it should still provide an idea of how often components are used."

2022-12-06 16:52 UTC, blurbyte commented on doc-site/pages/overview/adoption.tsx
> +        <Notification
Updated description, should be fine at the bottom.

2022-12-07 13:34 UTC, ixTec approved these changes
Approved
![image](https://user-images.githubusercontent.com/9938773/206192876-f7788574-94be-4643-984f-5d94507f6c1a.png)

2022-12-07 13:37 UTC, merged