[WF-659] Fix Notification decor and icon z-index
datacamp/waffles pull request #103
Opened 2022-10-04 10:20 UTC by blurbyte

# Fix Notification decor and icon z-index

## [WF-659](https://datacamp.atlassian.net/browse/WF-659)

## Changes

`Notification` decorative element z-indexes were too high, and were causing problems with `Tooltip`.

### 🔧 Minor Changes

- Decrease z-index of `Notification` decor and icon

## Screenshot(s):

Before:
<img width="283" alt="Screenshot 2022-10-04 at 12 00 26" src="https://user-images.githubusercontent.com/20565536/193795316-2a718c5f-f560-4440-ae5c-4bb0b15aecb5.png">

After:
<img width="291" alt="Screenshot 2022-10-04 at 12 08 38" src="https://user-images.githubusercontent.com/20565536/193795332-b4774d70-1ded-4d71-b28b-7c961967fcac.png">

2022-10-04 12:36 UTC, hermansje commented
Is a z-index needed at all?
I think the z-index can be removed from the icon and the icon background if the order of these divs is switched: https://github.com/datacamp/waffles/blob/c9d39d707a10bf6849964e0a596877e1310cef3b/src/notification-card/icon.tsx#L37-L38
If a z-index would be needed, it would only be needed on the first div and 1 would be enough.

2022-10-04 12:41 UTC, blurbyte commented
@hermansje Nice catch, you are totally right 👍.

2022-10-05 10:32 UTC, ixTec requested changes
Not sure we need to still have a z-index of the icon / icon wrapper

2022-10-05 10:32 UTC, ixTec commented on src/notification-card/styles.ts
>      width: ${tokens.sizing.small};
Do we even need to be setting a `z-index` for the icon wrapper here? If we're setting it to default, I think we're okay to just not have a z-index specified at all?

2022-10-05 11:59 UTC, blurbyte commented on src/notification-card/styles.ts
>      width: ${tokens.sizing.small};
I prefer to keep it just a tad higher than 0 (when it's unspecified), just to avoid some weird possible glitches in future.

2022-10-05 12:31 UTC, ixTec approved these changes

2022-10-05 12:37 UTC, merged