WIP: [WF-569] Component documentation improvements
datacamp/waffles pull request #105
Opened 2022-10-07 15:40 UTC by ixTec

# Various documentation improvements

**Note: will continue to update this PR with additional component doc changes as I complete them**

## [WF-569](https://datacamp.atlassian.net/browse/WF-569)

## Changes

### 🔧 Minor Changes

- Updated best practices and usage guidelines the following components:
    - Asset
    - Avatar
    - Badge
    - Brand
    - Button
    - Empty State
    - Loader
    - Progress
    - Tooltip

### ❓ Misc Changes

- Fixed `best-practices` section margin when directly preceded by a `h3`
- Fixed typo in Tooltip `complex-content` example 
- Fixed margin issue with having a `Notification` at the top of a docs page

2022-10-17 14:19 UTC, blurbyte requested changes
Looks great🥇!

A few things to consider to make it a bit more readable / consistent:
- in general I would avoid using bold / strong and use emphasis instead; but there are a few places when bold makes sense, like in 'critical' in Heading best practices
- not a big fan of number in parenthesis, e.g. something three (3), either omit it or use a number
- in BestPractices list items start lower case (most of them) or upper case (Avatar)?
- single quotes or double quotes: 'Course progress' or "Course progress"

2022-10-17 14:19 UTC, blurbyte commented on doc-site/pages/components/loader.mdx
> +    - Provide a simple but descriptive `aria-label` as context for screen readers&mdash;such as 'Loading user profile'
Shouldn't we make aria label mandatory? Also usage of `aria-live` / `aria-busy` in one of the examples should be great.

2022-10-17 14:19 UTC, blurbyte commented on doc-site/pages/components/paragraph.mdx
> +<Layout title="Paragraph" description="Used for styling blocks of text using DataCamp's styling.">
Maybe 'Used for styling blocks of text'. I would also mention here that's the default / go-to component for text.

2022-10-17 14:19 UTC, blurbyte commented on doc-site/pages/components/paragraph.mdx
> +he `Paragraph` component offers three (3) different `size` values to choose from: `small`, `medium` and `large`. In most cases, the default `size` should be used.
Missing 'T', not a fan of (3) 😄

2022-10-17 14:19 UTC, blurbyte commented on doc-site/pages/components/progress.mdx
> +When using the default `mode`, any values for `min` and `max` can be provided and a percentage is calculated internally. This includes values that would result in a percentage over `100%`. This perce
Maybe add 'Default continuous mode' heading above.

2022-10-17 14:19 UTC, blurbyte commented on doc-site/pages/components/tooltip.mdx
> +    - use `Help`/`HelpCircle` [Icon](/components/icon) where trigger is not related
I think it should be icon-only button with `Help` / `HelpCircle` icon. But yeah this whole pattern is a bit sus.

2022-10-18 13:07 UTC, ixTec commented on doc-site/pages/components/badge.mdx
> +They should **never** be interactive and instead a [Button](/components/button) or the future `Tag` component used if interaction is desired.
Hopeful optimism from me here 😄

2022-10-18 13:32 UTC, ixTec commented on doc-site/pages/components/icon.mdx
> -### Icon is not a Button
I have it in the same place as before (as a heading in Best Practices), below the general best practices

2022-10-18 13:42 UTC, ixTec commented on doc-site/pages/components/tooltip.mdx
> +    - use `Help`/`HelpCircle` [Icon](/components/icon) where trigger is not related
Updated but yeah, it's a bit of a unclear use case as we don't really have a recommended standard yet (but this would be _my_ recommendation at least 😄 )

2022-10-18 14:03 UTC, ixTec commented on doc-site/pages/components/loader.mdx
> +    - Provide a simple but descriptive `aria-label` as context for screen readers&mdash;such as 'Loading user profile'
Agreed, `aria-label` should probably be mandatory. I have raised https://datacamp.atlassian.net/browse/WF-669 for this

2022-10-19 09:46 UTC, ixTec commented
- Updated emphasis across changes. I've kept usage for strong words such as "never", "not" and "critical", just to force the point more.
- Removed numbers in parenthesis 
- Double quotes should be used because we're following the US standards for grammar etc, instead of UK English (where it should be single quotes in most places)

2022-10-19 11:29 UTC, blurbyte requested changes
Nice updates 👏 . There are still a few things to improve:

- think we wanted to capitalize component name in props docs too (as in `Button`)
- still missing 'Icon is not a Button' heading in `Icon`
- for some components items on the `BestPractices` list start with uppercase and for others lowercase - would be nice to make it consistent
- `aria-live` code example for `Loader` could be improved, and to make content look a bit nicer maybe put it on beige `beigeLight` with rounded corners (as in `Resizable` examples)

2022-10-19 11:29 UTC, blurbyte commented on doc-site/pages/components/code-block.mdx
> +It should never be placed inline and instead the [Code](/components/code) component should be used.
Most likely 'never' should be bold here.

2022-10-19 11:29 UTC, blurbyte commented on doc-site/pages/components/loader.mdx
> +      If you're looking for a loading Button variant, see our{' '}
Don't think button here should be capitalized here, since it's just generic use case of loader inside button.

2022-10-19 11:29 UTC, blurbyte commented on doc-site/pages/components/loader.mdx
> +    - provide a simple but descriptive `aria-label` as context for screen readers&mdash;such as 'Loading user profile'
Should be "Loading user profile"?

2022-10-19 11:29 UTC, blurbyte commented on doc-site/pages/components/paragraph.mdx
> +To highlight the content of importance, use regular `strong` or `em` elements. `Paragraph` also offers a more subtle `secondary` `variant` for use with less important or supportive content. On top of
Maybe `variant="secondary"`, will be a bit nicer to look at.

2022-10-19 11:29 UTC, blurbyte commented on doc-site/examples/loader/aria-live.tsx
> +function Example() {
It could be written in a bit more straightforward / cleaner way using only 1 state var instead of 3 (and trying to sync between them):

- for state use something along the lines `const [status, setStatus] = useState<'initial' | 'loading' | 'final'>('initial')` (or something similar)
- for content you can create `renderContent()` function with switch inside rendering appropriate content based on status
- for button just derive functionality / label from status

2022-10-19 11:52 UTC, ixTec commented on doc-site/pages/components/loader.mdx
> +      If you're looking for a loading Button variant, see our{' '}
Good point. I think it can be viewed in either way, but I believe the stronger wording is towards a generic button so I'll update this

2022-10-19 15:23 UTC, ixTec commented
Updated based on changes.

- I've replaced "Icon is not a Button" header with "Icon within a Button", as the text within this section clarifies that an Icon is not a Button in addition to the rest. I think this is a bit more suitable for the approach we're taking for the docs
- Updated casing of component name in prop docs for all components, but won't be tackling updating the other component's documentation beyond that in this PR (will be future work for either of us, as discussed)

2022-10-20 09:18 UTC, blurbyte requested changes
Looks great, love how consistent it is ❤️ , and `aria-live` example is superb.
I have a few minor remarks, otherwise we should be ready to merge today.

<iframe src="https://giphy.com/embed/8Iv5lqKwKsZ2g" width="480" height="201" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/dicaprio-draw-serial-8Iv5lqKwKsZ2g">via GIPHY</a></p>

2022-10-20 09:18 UTC, blurbyte commented on doc-site/pages/components/paragraph.mdx
> +To highlight the content of importance, use regular `strong` or `em` elements. `Paragraph` also offers a more subtle `variant="secondary`" for use with less important or supportive content. On top of
Quotation mark should be inside ticks for `variant="secondary"`.

2022-10-20 09:18 UTC, blurbyte commented on doc-site/examples/loader/aria-live.tsx
> +  return (
I think it would look a bit cleaner (and no extra styles for button will be required):
<img width="857" alt="Screenshot 2022-10-20 at 11 13 33" src="https://user-images.githubusercontent.com/20565536/196908138-30d6764e-be63-435b-8676-cfe99a661bbb.png">

2022-10-20 09:30 UTC, blurbyte requested changes

2022-10-20 09:30 UTC, blurbyte commented on doc-site/examples/loader/aria-live.tsx
> +const INITIAL_CONTENT = (
Don't think it's worth extracting these to separate consts, I would put them directly in switch.

2022-10-20 10:13 UTC, ixTec commented on doc-site/examples/loader/aria-live.tsx
> +const INITIAL_CONTENT = (
I think our examples should best practices in general where possible, so I've put these as consts so that they're not redefined each rerender when it's static content

2022-10-20 11:32 UTC, blurbyte commented on doc-site/examples/loader/aria-live.tsx
> +  return (
I'm not sure about this rule tbh. It makes sense for Dialog (maybe for Card), but otherwise it's close to being anti-pattern, since users tend to scan long pages from left to right, therefore you want to put most important CTAs to the left.

2022-10-20 11:33 UTC, blurbyte commented on doc-site/examples/loader/aria-live.tsx
> +const INITIAL_CONTENT = (
Makes sense.

2022-10-20 13:22 UTC, blurbyte approved these changes
Let's merge 🚀.

2022-10-20 14:17 UTC, merged