[WF-635] Add banner `mode` to Notification
datacamp/waffles pull request #108
Opened 2022-10-11 12:41 UTC by ixTec

# Add new banner `mode` to Notification

## [WF-635](https://datacamp.atlassian.net/browse/WF-635)

## Changes

### 🚀 Major Changes

- Added `mode` prop to `Notification` component
    - defaults to `inline` which has no change in behaviour or appearance to existing Notification
    - `banner` value shows Notification as a top-banner style (see images below)

## Screenshot(s):
![Screenshot 2022-10-11 at 13 36 13](https://user-images.githubusercontent.com/9938773/195092047-cbc1354d-fd3e-4fd2-a72a-9862b5205f22.png)
![Screenshot 2022-10-11 at 13 37 02](https://user-images.githubusercontent.com/9938773/195092264-6778e312-fbed-40dc-be5b-7637526cc83d.png)

2022-10-12 12:17 UTC, blurbyte requested changes
Looks good, and seems to behave nicely on different resolutions.

Not really sure about `isIconCentered` var, doesn't seem to do anything.

I think we are missing a few tests here and there. Would be nice to have at least 1 jest snapshot of notification in banner mode.

Maybe it would be good idea to put some limit on how wide content could be (for `ContentContainer` it's 1200px for example). Here, albeit scenario is highly unlikely, it looks a bit weird:
<img width="1727" alt="Screenshot 2022-10-12 at 14 17 24" src="https://user-images.githubusercontent.com/20565536/195340477-e90791ea-e145-4e1c-a124-29c3b583d71b.png">

2022-10-12 12:17 UTC, blurbyte commented on src/notification-card/notification-card-internal.tsx
> +  const isIconCentered = closable && isContentCentered;
What exactly is the purpose of this var? Couldn't tell a difference on how notification rendered with the styles it was adjusting commented out.

2022-10-12 12:17 UTC, blurbyte commented on src/notification/notification-internal.tsx
> +  /* Whether to display the notification as a banner or inline mode. */
Maybe 'Whether to display the notification as a banner or as an inline content.'?

2022-10-12 12:48 UTC, ixTec commented on src/notification-card/notification-card-internal.tsx
> +  const isIconCentered = closable && isContentCentered;
It's to add the required opposing margin when the notification is closable, which is now set as `margin-right: auto` so we need a `margin-left: auto` on the left most element as the Icon/heading/title aren't wrapped separate to the close button. See below screenshot for how it looks without:

![Screenshot 2022-10-12 at 13 46 03](https://user-images.githubusercontent.com/9938773/195346383-9d584457-0a93-48a9-bf21-e009dac138b0.png)

2022-10-12 14:06 UTC, blurbyte commented on src/notification-card/notification-card-internal.tsx
> +  const isIconCentered = closable && isContentCentered;
Ah, ok.

2022-10-13 10:13 UTC, blurbyte requested changes
Nice improvements to tests!
We are close to merging it, but there are a few issues:

1. Tbh I would completely skip that width limit for inline mode (it's very unlikely usage scenario overall). Probably It looks better without it, and there is an issue with action button:

_Before_
<img width="1139" alt="Screenshot 2022-10-13 at 11 59 07" src="https://user-images.githubusercontent.com/20565536/195569425-ded20a14-35fd-4a20-9be4-fbbc77f5df76.png">

_Now_
<img width="1139" alt="Screenshot 2022-10-13 at 12 00 58" src="https://user-images.githubusercontent.com/20565536/195569687-7d43685c-2d4c-4872-9c09-9a6cda61326f.png">

2. Width limitation in banner mode should align nicely with `ContentContainer`, which is not a case atm (would be ideal if left icons align nicely in scenario shown below):
<img width="1357" alt="Screenshot 2022-10-13 at 12 06 32" src="https://user-images.githubusercontent.com/20565536/195570013-08561262-cc3d-48cb-8114-d982aca06fc2.png">

2022-10-14 08:52 UTC, blurbyte approved these changes
Looks good, let's merge 🚀.

2022-10-14 09:04 UTC, merged