[WF-672] Inverted Card
datacamp/waffles pull request #116
Opened 2022-11-01 12:57 UTC by blurbyte

# Inverted Card

## [WF-672](https://datacamp.atlassian.net/browse/WF-672)

## Changes

### 🚀 Major Changes

-  Added `inverted` Card variant.
  - Implemented `Card.HeadstoneItem`, which should improve usability of the `Card` component, so user don't have to worry about setting proper color variant and size of `Avatar`. It's still possible to use custom components for headstone.

## Screenshot(s):
<img width="819" alt="Screenshot 2022-11-01 at 13 51 12" src="https://user-images.githubusercontent.com/20565536/199237270-45bf3c15-99d9-4044-85f9-d8043d9e7730.png">

2022-11-01 15:41 UTC, ixTec requested changes
Few minor comments, but otherwise looks good!

2022-11-01 15:41 UTC, ixTec commented on src/card/styles.ts
> +      ${hexToRgba(inverted ? tokens.colors.white : tokens.colors.navy, 0.15)};
Do we also want to have a different coloured box shadow on hover for inverted too?

2022-11-02 10:33 UTC, blurbyte commented on src/card/styles.ts
> +      ${hexToRgba(inverted ? tokens.colors.white : tokens.colors.navy, 0.15)};
Not according to designs. Not sure how to make it visible (besides making it light grey, which will look weird).

2022-11-02 10:33 UTC, blurbyte commented on src/card/headstone-item.tsx
> +function HeadstoneItem({
Good idea.

2022-11-02 15:27 UTC, ixTec approved these changes

2022-11-03 09:36 UTC, merged