[WF-677] Add override for Notification close button
datacamp/waffles pull request #121
Opened 2022-11-08 13:36 UTC by ixTec

# Add override for Notification close button

## [WF-677](https://datacamp.atlassian.net/browse/WF-677)

## Changes

### 🚀 Major Changes

- Exposed `Notification.CloseButton` to be used in the new `closeButton` prop in order to specify custom close button overrides

2022-11-09 10:05 UTC, blurbyte requested changes
Well done. Pretty much what we need here.

Maybe we should make it a bit more generic and introduce simple `overrides` API (basically collection of predefined slots). Such consistent pattern of internal components can be used to improve other complex components. During next steering group we can for example ask ppl for their preferred candidates for adding it.

2022-11-09 10:05 UTC, blurbyte commented on src/notification/notification-internal.tsx
> +  closeButton,
Maybe we should take it as an opportunity and introduce some basic `overrides` API? It would be basically a collection of predefined slots of internal components you would be able to replace with your custom ones. 

So in this case: `<Notification overrides={{ CloseButton: <CustomCloseButton /> }}` />`.
And by default it will use our components. So in `notification-internal` it would be something like this:
```
const { CloseButton: CloseButtonOverride } = overrides;

 // isValidElement from React
 // InternalCloseButton is Notification.CloseButton
const CloseButton = isValidElement(CloseButtonOverride) || InternalCloseButton;
```
It could solve the issue with (although rare) styling / customizing internals for some more complex components (lika Dialog).

What do you think? Cold be nice experiment, and later we can improve other components with it potentially.

2022-11-09 10:05 UTC, blurbyte commented on src/notification/notification-internal.tsx
> +type NotificationProps = NotificationClosable | NotificationPersistent;
Don't think we have to be that strict here. If someone will make `closable` conditional it will make their life harder overall.

2022-11-09 10:12 UTC, blurbyte requested changes

2022-11-09 10:12 UTC, blurbyte commented on src/notification/__tests__/notification.spec.tsx
> +  it('renders custom close button', async () => {
Maybe would be worth testing if `onClose` and custom button `onClick` are triggered correctly?

2022-11-09 11:30 UTC, ixTec commented on src/notification/notification-internal.tsx
> +  closeButton,
As discussed, leaving this as future work for when we overhaul typings and apis for components

2022-11-09 13:44 UTC, ixTec commented on src/notification/notification-internal.tsx
> +type NotificationProps = NotificationClosable | NotificationPersistent;
`closeButton` shouldn't be provided if the the Notification isn't `closable`. Should be very easy to handle as long as they wrap both `closable` and `closeButton` in whatever conditional they use

2022-11-09 14:24 UTC, blurbyte commented on src/notification/notification-internal.tsx
> +type NotificationProps = NotificationClosable | NotificationPersistent;
I just think technically there is no harm if someone whats to pass custom button which is not even visible, most likely for future use e.g. to conditionally switch between closable. But I'm also fine with leaving this more advanced typings, it just could be a bit cumbersome from DX perspective.

2022-11-09 15:23 UTC, blurbyte requested changes
We are really close to merging. Have just a few minor remarks. 
I would maybe consider changing `closeButtonOverride` to just `closeOverride`. It just gives me some strong jQuery vibes for whatever reason :). But be free to leave it more explicit, not a big deal.

2022-11-09 15:23 UTC, blurbyte commented on src/notification-card/notification-card-internal.tsx
> +  function handleClick() {
I would refactor whole close button handling to something a bit more cleaner, e.g.
```
function renderCloseButton() {
    function handleClick() {
      closeButtonOverride?.props.onClick?.();
      onClose?.();
    }

    if(closable) {
      return closeButtonOverride ? cloneElement(closeButtonOverride, {
        inverted,
        onClick: handleClick
      }) : <CloseButton inverted={inverted} onClick={onClose} />
    }

    return null;
  }
```
and in component itself just 
```
<section>
  ...
  {renderCloseButton()}
</section>
```

2022-11-09 15:23 UTC, blurbyte commented on src/notification-card/notification-card.tsx
> +  CloseButton,
Should we mention this subcomponent in docs (probably not, but not sure if omitting it was intentional)?

2022-11-09 15:23 UTC, blurbyte commented on src/notification/__tests__/notification.spec.tsx
> +  it('renders custom close button with onClose and onClick handlers working', async () => {
Maybe 'when custom close button is provided, appropriate onClose and onClick handlers are fired'?

2022-11-09 15:23 UTC, blurbyte commented on src/notification/notification-internal.tsx
> +  /* Custom close button override. In most cases, still use `Notification.CloseButton`. */
Maybe 'Custom close button component. In general use `Notification.CloseButton` subcomponent.'?

2022-11-09 15:23 UTC, blurbyte commented on doc-site/examples/notification/custom-close.tsx
> +        <Notification.CloseButton data-trackid="custom track id" />
Data attrs should be in general kebab cases, so `custom-track-id`.

2022-11-09 15:23 UTC, blurbyte commented on src/notification/__tests__/notification.spec.tsx
> +            data-testid="Custom close button"
Should be `custom-close-button`.

2022-11-09 15:31 UTC, ixTec commented on src/notification/card.tsx
> +  onClose: () => void;
It will always be provided, as `notification-internal` has the `handleClose` function passed through

2022-11-09 16:36 UTC, ixTec commented on src/notification-card/notification-card.tsx
> +  CloseButton,
Unintentional, so I've added it to docs! Best to have it documented, just like dialog close button

2022-11-10 10:09 UTC, ixTec commented
Leaving `closeButtonOverride` as is, because I think `closeOverride` is a little confusing (could imply it overrides close behaviour etc)

2022-11-10 11:02 UTC, blurbyte approved these changes
Let's merge 🦀 .

https://media.giphy.com/media/LcfBYS8BKhCvK/giphy.gif

2022-11-10 11:17 UTC, merged