[WF-674, WF-686, WF-688, WF-700] Update Dialog internals, improve accessibility and add decorative header variant
datacamp/waffles pull request #126
Opened 2022-11-23 17:04 UTC by ixTec

# Update Dialog internals, improve accessibility and add decorative header variant

- [WF-674](https://datacamp.atlassian.net/browse/WF-674)
- [WF-686](https://datacamp.atlassian.net/browse/WF-686)
- [WF-688](https://datacamp.atlassian.net/browse/WF-688)
- [WF-700](https://datacamp.atlassian.net/browse/WF-700)

## Changes

### 🚨 Breaking Changes

- `Dialog`, `AlertDialog` and `Drawer` now have their `id`, `aria-describedby` and `aria-labelledby` set automatically internally

### 🚀 Major Changes

- `Dialog.Button` now supports polymorphic typing via the `as` prop
- `Drawer `now relies more heavily on `Dialog` internally
- `AlertDialog` now directly uses `Dialog.Footer` and `Dialog.Body` internally
- `Dialog`, `AlertDialog` and `Drawer` now support `closeButtonOverride` prop, for custom close button 

### 🔧 Minor Changes

- `Dialog` content and buttons can now be center aligned via `alignCenter` prop
- Removed `border-top` from `Dialog.Footer` and `Drawer.Footer`
- `Overlay` now uses `floating-ui` overlay as a base
- Extracted Icon logic from `Notification` into separate `NotificationIcon` component
- Fixed issue with icon colour for `upgrade` variant `Notification`

### ❓ Misc Changes

- Removed `react-focus-on` dependency. Functionality has been replaced/refactored using `floating-ui`
- Updated `Drawer` docs to reflect `Dialog` (removed most prop tables)
- Fixed casing within buttons of several examples

## Screenshot(s):

![Screenshot 2022-11-29 at 16 00 24](https://user-images.githubusercontent.com/9938773/204579659-0cfbdf4a-e99b-4ea9-b023-4d21d7a84d6e.png)
![Screenshot 2022-11-29 at 16 03 03](https://user-images.githubusercontent.com/9938773/204580280-3b179c1c-b175-47e4-b14d-f4f048739c69.png)
![Screenshot 2022-11-29 at 16 00 32](https://user-images.githubusercontent.com/9938773/204579681-8c312b4d-9e5b-4b87-943a-61a249d4c30b.png)
![Screenshot 2022-11-29 at 16 01 43](https://user-images.githubusercontent.com/9938773/204579957-e37015ac-0a06-4a54-9b43-5eb3e46c2b2f.png)
![Screenshot 2022-11-29 at 16 01 50](https://user-images.githubusercontent.com/9938773/204579981-92aaf7c3-6931-4cee-8dd2-249ce228f1c5.png)
![Screenshot 2022-11-29 at 16 01 57](https://user-images.githubusercontent.com/9938773/204580015-41b90cbf-df92-4bc8-9f9c-b5f50cbbe8cc.png)
![Screenshot 2022-11-29 at 16 02 03](https://user-images.githubusercontent.com/9938773/204580042-b06a44f9-f0a3-46b1-8066-749c772a029c.png)
![Screenshot 2022-11-29 at 16 04 01](https://user-images.githubusercontent.com/9938773/204580496-2992861d-ac74-4ac9-a973-7ddb16399999.png)

2022-11-30 13:42 UTC, blurbyte requested changes
Looks really nice so far 🎉 ! Addressed some Visual and Examples issues first. 

## Visual

1. All buttons for `Dialog` and `Drawer` should be right aligned with main CTA as the rightmost one (when not `alignCenter`), with `spacing.tokens.small` (8px) gap between them
2. Bottom padding of `Dialog.Footer` and `Drawer.Footer` should be increased to `spacing.tokens.large` (24px)
3. I think `CloseButton` in regular and decorative headers should be in the same position - I'd suggest `top: 6px` and `right: 6px`.
4. Decorative header height is incorrect - should be `44px` of dark bgr and `4px` of color decor. Although here I would try `CloseButton` placement from point 3. and than adjust dark bgr height, so X is exactly in the middle.
5. Missing thin border around decorative header (top, left, right, 15% white)
6. Missing hover color for decorative header `CloseButton` - should 10% white
7. On _mobile_, layout of buttons in Dialog / Drawer / AlertDialog `Footer` should be as following:
For 2 buttons they should be next to each other but taking all the space (most likely `grid-template-columns: 1fr 1fr` should be enough):
<img width="338" alt="Screenshot 2022-11-30 at 14 35 17" src="https://user-images.githubusercontent.com/20565536/204810808-f062904c-03a5-4f0d-8cbf-3f625e6bc6b4.png">
For 3+ buttons they should be stacked vertically (ignore incorrect spacing in the example, should always be 8px):
<img width="368" alt="Screenshot 2022-11-30 at 14 39 03" src="https://user-images.githubusercontent.com/20565536/204811012-c0401bb1-58a3-46cf-beda-d4d6ec83425a.png">

## Examples

1. Please don't use 'Lorem ipsum' in examples, shouldn't be hard to find something in our products copy. In tests it's fine.
2. In 'Decorative header' example I would suggest using radios to set preferred variant as in Menu 'Placement':
<img width="671" alt="Screenshot 2022-11-30 at 14 22 40" src="https://user-images.githubusercontent.com/20565536/204807435-ca176a41-7a78-4a7a-8cc2-23467b82a047.png">

2022-11-30 16:54 UTC, blurbyte requested changes

2022-11-30 16:54 UTC, blurbyte commented on src/notification-icon/notification-icon.tsx
> +  size?: 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';
Do we need all these sizes here? I think currently we are using only `medium` and `large`. Would make `backgroundStyle` a bit more straightforward.

2022-11-30 16:54 UTC, blurbyte commented on src/notification-icon/styles.ts
> +export function iconWrapperStyle() {
I think since it's separate component now (so we are in 'icon' context) we can easily call it just `wrapperStyle`.

2022-11-30 16:54 UTC, blurbyte commented on src/notification-icon/styles.ts
> +export function iconBackgroundStyle({
Similar to wrapper, we can call it `backgroundStyle`.

2022-11-30 16:54 UTC, blurbyte commented on src/notification-icon/styles.ts
> +  const radius =
Imho I would just handle 2 cases explicitly, the ones which are currently in use: medium and large. Or if we want to keep all these sizes probably it would be more straightforward to just declare in our usual map:
```
const radiusSizeMap = {
  xsmall: 4,
  small: 6,
  medium: 6
  ...,
  xlarge: 8
}
```

2022-11-30 16:54 UTC, blurbyte commented on src/overlay/overlay.tsx
> +    <FloatingOverlay
Really nice, simplified styling greatly 👍 .

2022-11-30 16:54 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +  idPrefix?: string;
Not really sure if we need it. Don't think it really matters if it will be different for `AlertDialog` and `Drawer`. Should be fine with `modal` for all cases.

2022-11-30 17:05 UTC, ixTec commented on src/dialog/close-button.tsx
>      <Button
Completely overlooked this 🤦‍♂️

2022-12-01 15:05 UTC, blurbyte requested changes
Some general remarks about tests and code structure.

1. Really love that it was possible to keep the same API for footer buttons 👏 
2. Really clean appraoch with a context overall
3. Not really sure if we need ID prefix and different IDs for heading and body
4. `Drawer` is rather broken. There was a reason it had these nested wrappers. 
Anyway it should look like this on mobile, aside some stylistic changes to footer:
<img width="396" alt="Screenshot 2022-12-01 at 15 51 02" src="https://user-images.githubusercontent.com/20565536/205086919-1546a36c-1f50-4696-acb8-2d09a125b24e.png">
But looks like this:
<img width="399" alt="Screenshot 2022-12-01 at 15 50 56" src="https://user-images.githubusercontent.com/20565536/205087027-33c7dfa5-ab1a-45cf-905f-a49e487b6adb.png">
5. Header variants examples and e2e could be improved slightly

2022-12-02 09:21 UTC, ixTec commented on src/notification-icon/notification-icon.tsx
> +  size?: 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';
Fair point, I can tidy this up along with the idea of a map for the values instead

2022-12-02 09:35 UTC, ixTec commented on src/dialog/footer.tsx
> +        return child.type === Button && child.props.autoFocus
This is a fair point, although I believe we shouldn't be trying to focus non-button content either...

The `autoFocus` prop is a custom prop for our `Button` and isn't the native behaviour (which only autofocuses first instance on page load), so I think it's a good idea to restrict the attempted behaviour to our Buttons still. What do you think?

2022-12-02 09:41 UTC, ixTec commented on src/dialog/dialog-internal.tsx
> +  function childConfig() {
Looking at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby, it seems aria-describedby should be provided unless the content does not have a descriptive purpose. In your example, where forms etc are provided then a consumer should provide `aria-label` on the `Dialog` instead. I'll add support to not add `aria-describedby` if `aria-label` is provided. 

As for the actual function, we could refactor into a hook here, as long as it reruns if `children` changes. I'll also make this improvement

2022-12-02 09:44 UTC, ixTec commented on src/dialog/dialog-internal.tsx
> +  idPrefix?: string;
I think `modal` is too generic for what we're doing, and it doesn't hurt to be more specific with our ids here, especially where some have styling overwritten etc

2022-12-02 10:17 UTC, ixTec commented on src/dialog/dialog-internal.tsx
> +  const id = `${idPrefix}-${useId()}`;
Raised https://datacamp.atlassian.net/browse/WF-711 to handle future `Modal` component refactor

2022-12-02 10:19 UTC, ixTec commented on src/dialog/dialog-internal.tsx
> +  idPrefix?: string;
Raised https://datacamp.atlassian.net/browse/WF-711 as discussed

2022-12-02 14:40 UTC, ixTec commented on doc-site/examples/dialog/decorative-header.tsx
> +  const [isOpen, setIsOpen] = useState([false, false, false, false, false]);
Great suggestion!

2022-12-02 15:28 UTC, ixTec commented on src/drawer/drawer-internal.tsx
> -import Panel from './panel';
The same structure is used within Dialog (overlay and panel separate), so shouldn't actually be any different, but I don't have a device to test for sure unfortunately.

I fixed Drawer responsive behaviour overall, as it was actually still broken before and not adhering to max-width for below medium

2022-12-05 09:06 UTC, blurbyte commented on src/dialog/footer.tsx
> +        return child.type === Button && child.props.autoFocus
It's fine :)

2022-12-05 12:24 UTC, blurbyte requested changes
We are pretty close to merging it. Got some ideas around `idPrefix` and `bodyId`, but I guess it could be tackled in next PR.

2022-12-05 12:24 UTC, blurbyte commented on src/notification-card/styles.ts
> +      /* margin-left: auto; */
It's commented out, so I assume we don't need it at all.

2022-12-05 12:24 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +  const [bodyId, setBodyId] = useState<string>();
I'm not convinced we need `bodyId` at all (same for `idPrefix`). Anyway I think we will want 1 more PR for modals anyway to put all shared stuff in `Modal` internal component. Also most likely we want to expose `useDialog` hook, which has some other implications.
So for now we can leave it as it is, and discuss these 2 things tomorrow.

2022-12-08 10:21 UTC, blurbyte requested changes
Just a few very minor things to update.

2022-12-08 10:21 UTC, blurbyte commented on doc-site/pages/components/dialog.mdx
> +If `Dialog.Body` contains non-descriptive content (e.g. form elements), then `aria-label` should be provided on the main `Dialog` element to provide context of the content.
I'd say `Notification` should be used here.

2022-12-08 10:21 UTC, blurbyte commented on src/dialog/header.tsx
> +  customIconOverride?: JSX.Element;
I think calling `customIcon` should be enough.

2022-12-08 10:21 UTC, blurbyte commented on src/dialog/header.tsx
> +  /* Mode of the dialog. */
Probably would be good idea to explain a bit more (with 1 extra sentence or sth) what it actually does.

2022-12-08 10:21 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +  const didMount = useRef(false);
Would put some new lines between some related items to 'group' them a bit.

2022-12-08 10:21 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +import AlertHeader from '../alert-dialog/header';
Would add TODO here, since we usually don't import components that way. Probably will be solved nicely after refactoring shared stuff into `Modal`.

2022-12-08 10:55 UTC, blurbyte requested changes

2022-12-08 10:55 UTC, blurbyte commented on src/dialog/debug-messages.ts
> +  MISSING_HEADER: 'Dialog requires a `Dialog.Header` child component.',
We can add a bit of reasoning here, e.g. `For accessibility reasons...`

2022-12-08 10:55 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +  }, [ariaLabel, children, headerId, id]);
Don't think `headerId` is needed here.

2022-12-08 10:55 UTC, blurbyte commented on src/dialog/dialog-internal.tsx
> +  const [headerId, setHeaderId] = useState<string>();
I think setting `null` as initial value for both `headerId` and `bodyId` makes it a bit clearer it _might_ not exist.

2022-12-08 10:55 UTC, blurbyte commented on src/dialog/button-internal.tsx
> +    autoFocus,
I think we can easily omit all of these here and leave only `as`, `children`, and `...restProps`.

2022-12-08 11:00 UTC, ixTec commented on src/dialog/debug-messages.ts
> +  MISSING_HEADER: 'Dialog requires a `Dialog.Header` child component.',
Leaving as is, as discussed, as the documentation covers a more detailed explanation and these errors should be kept simple for the most part

2022-12-08 11:16 UTC, blurbyte approved these changes
Let's merge 🚀 

![cocktail party](https://media.giphy.com/media/u4CY9BW4umAfu/giphy.gif)

2022-12-08 11:17 UTC, merged