[WF-694] Old content guidelines
datacamp/waffles pull request #128
Opened 2022-11-29 12:40 UTC by blurbyte

# Insert Description Here

## [WF-694](https://datacamp.atlassian.net/browse/WF-694)

## Changes

### 🚀 Major Changes

- Ported content guidelines from Old Waffles without any major changes (only removed nested bullet lists)

### ❓ Misc Changes

- Updated `slugify` docs utility to be stricter, so it removes dots (.), e.g. before change it was transforming 'Data, data.frame' to 'data-data.frame', and now it's better 'data-dataframe'.

## Screenshot(s):
<img width="1493" alt="Screenshot 2022-11-29 at 13 29 09" src="https://user-images.githubusercontent.com/20565536/204531616-618c7c1d-374e-43d9-8947-a1b5bf3a1c42.png">

2022-11-29 16:13 UTC, ixTec requested changes
I think the crowdedness of the side nav will be mostly resolved once we introduce collapsible sections in it (and have all but active collapsed). We probably don't want to introduce the top-level pills until we have more design-focused content in the future.

As we're just handling this in a "copy over content, but don't review" mode, I haven't looked too closely for typos etc, but it's important we add a `Notification` at the top of these pages to say that this content is under review / needs review so may not be accurate.

2022-12-02 14:14 UTC, ixTec requested changes
A few minor comments for grammar etc

In terms of notification, I think it's still good idea to include it because people _are_ currently using the information but we're aware we need to update / review it properly in the future

2022-12-02 14:14 UTC, ixTec commented on doc-site/pages/content/grammar.mdx
> +
Not a comment on the PR, but I hate all three of these as concepts so much 😆 seems ridiculous they're actually rules

2022-12-02 14:14 UTC, ixTec commented on doc-site/pages/content/grammar.mdx
> +In general, ampersands should not be used in DataCamp copy, and should never be used in a complete sentence. Ampersands should be used very sparingly, only in copy that does not end in a punctuation
"... used ~~very~~ sparingly..."
sparingly implies very

2022-12-02 14:14 UTC, ixTec commented on doc-site/pages/content/grammar.mdx
> +The Oxford comma (see examples below) should continue to be used in most body copy, such as course descriptions, the main text of blog posts and emails, and long-form articles. Because we are frequen
"... . *as* we are frequently..."

2022-12-02 14:14 UTC, ixTec commented on doc-site/pages/content/terminology.mdx
> +    - self-join
this best practices section is probably redundant because we explicitly say not to do this in the text above

2022-12-05 08:35 UTC, blurbyte commented on doc-site/pages/content/course-naming.mdx
> +  <BestPractices.Discouraged>
Good catch 👍

2022-12-05 08:37 UTC, blurbyte commented on doc-site/pages/content/terminology.mdx
> +    - self-join
I would leave it, makes it super clear.

2022-12-06 10:47 UTC, ixTec approved these changes

2022-12-06 11:12 UTC, merged