[WF-673] Pagination
datacamp/waffles pull request #133
Opened 2022-12-20 11:51 UTC by ixTec

# Add new Pagination component

## [WF-673](https://datacamp.atlassian.net/browse/WF-673)

## Changes

### 🚀 Major Changes

- Added new `Pagination` component

## Screenshot(s):
![Screenshot 2022-12-20 at 11 50 17](https://user-images.githubusercontent.com/9938773/208660424-d657fed4-1cc2-4d0a-a6fa-85cf82db47e8.png)
![Screenshot 2022-12-20 at 11 50 32](https://user-images.githubusercontent.com/9938773/208660425-3263cc35-8796-4105-a7db-b8dedfe6fb8b.png)

2022-12-21 16:06 UTC, blurbyte requested changes
Looks really nice, and API is really well thought 👏 .

Noticed that hover style is activated even when next / prev button is disabled (only for light mode):
<img width="522" alt="pagination-hover-on -disabled" src="https://user-images.githubusercontent.com/20565536/208948839-a96e318c-a4ff-4bc6-8adf-912824cb4afa.png">

When seeing it in action I am not convinced this color change for button is good idea when it enters disabled state. Personally I think using 60% opacity should be enough and would look better (just our regular disabled style for button). We should show it to Maria.

Also not really sure what is going on, but when navigating with keyboard when focusing for example page 8 actually page 7 is selected. Looks like it's incrementing pages one by one instead of jumping directly to focused one:

[problem-with-navigation](https://user-images.githubusercontent.com/20565536/208949580-741f7262-1915-40b8-98a5-aae010606096.mp4)

2022-12-21 16:06 UTC, blurbyte commented on src/pagination/navigation.tsx
> +  variant: 'previous' | 'next';
I think `variant` name could be a bit confusing here, because button itself have its own `variant`.

2022-12-22 09:47 UTC, ixTec commented on src/pagination/navigation.tsx
> +    modifier: -1,
I think `increment` or `pageIncrement` indicate the number should increase and although we technically _increment_ by `-1`, I think it's a little less clear for that case still. Perhaps `pageModifer` - what do you think? @blurbyte

2022-12-22 09:49 UTC, ixTec commented on src/pagination/pagination.tsx
> +  !isValidPage(currentPage) && logError(MESSAGES.INVALID_ACTIVE_PAGE);
Nice catch - have switched these round so totalPages check is first and also added to `isValidPage` to ensure `totalPages` is considered in the check there

2022-12-22 09:51 UTC, ixTec commented on src/pagination/navigation.tsx
> +  variant: 'previous' | 'next';
renamed to `navigationVariant`

2022-12-22 10:49 UTC, ixTec commented on src/pagination/navigation.tsx
> +    modifier: -1,
Added comment to `modifier` instead

2022-12-23 11:05 UTC, blurbyte requested changes
Looks really nice, we should be able to merge today.

As for naming standarization: 
- when we pass an event prop to component we usually call it `**on**Something` (onClick, onChange).
- when we handle some event internally in the component we usually call it `**handle**Something`
I would move most of the logic from './pages' to './utils'.
We are missing a few e2e test.

2022-12-23 11:05 UTC, blurbyte commented on src/pagination/__tests__/pagination-inverted.story.tsx
> +const wrapperStyle = css`
Should have navy background.

2022-12-23 11:05 UTC, blurbyte commented on src/pagination/__tests__/pagination.e2e.ts
> +describe('Tabs', () => {
Should be 'Pagination' instead of 'Tabs'. I would also add some test of behavior:
1. what happens if I press Next / Previous when currentPage is min, max, and somewhere in the middle
2. test keybaord interactions (case which was previously broken)

2022-12-23 12:37 UTC, ixTec commented on src/pagination/pagination.tsx
> +  !totalPages && logError(MESSAGES.INVALID_ACTIVE_PAGE);
Totally missed I was calling `INVALID_ACTIVE_PAGE` instead of `INVALID_TOTAL_PAGES` 🤦

2022-12-23 12:53 UTC, ixTec commented on src/pagination/pagination.tsx
> +  useEffect(() => {
Not much point using `useCallbackRef` here, as the visible page buttons changes on each update

2022-12-23 13:22 UTC, ixTec commented on src/pagination/pages.tsx
> +    if (totalPages > 1) {
Leaving in `pages.tsx` as discussed

2022-12-23 13:39 UTC, ixTec commented on src/pagination/pagination.tsx
> +  useEffect(() => {
Focusing has to happen as a result of `isActive`, not from the click (as the elements will rerender after the `currentPage` change so I've left as is for simplicity

2022-12-23 16:22 UTC, blurbyte requested changes
Just 2 minor things updates to internals. Also noticed for whatever reason current page focus is always visible on first render, but I guess you can take care of it after I will be OOO.

2022-12-23 16:22 UTC, blurbyte commented on src/pagination/navigation.tsx
> +  function renderButton(children: React.ReactNode, { ...props }) {
Was thinking about it a bit and came up with something even simpler, what do you think?
```
function renderIconProp() {
    if(isAboveSmall && navigationVariant === 'previous') {
      return {
        iconLeft: variantMap[navigationVariant].icon
      }
    }
    ...other ones here...

    return null;
  }

  return (
    <li>
      <Button
      inverted={inverted}
      disabled={disabled}
      variant='plain'
      onClick={handleClick}
      css={navigationButtonStyle({
        inverted,
        navigationVariant,
      })}
      aria-label={variantMap[navigationVariant].ariaLabel}
      data-testid="pagination-navigation"
      {...renderIconProp()}
    >{isAboveSmall && variantMap[navigationVariant].label}</Button>
    </li>
  );
```
Could be called `renderExtraProps` if we need more bespoke props. Also I think we can get rid of `ariaLabel` from `variantMap` and just construct it based on label: `'${label} page'`.

2022-12-23 16:45 UTC, ixTec commented on src/pagination/navigation.tsx
> +  function renderButton(children: React.ReactNode, { ...props }) {
Great suggestion! I've kept the specific `ariaLabel` in `variantMap` to avoid having to handle `charAt(0).upperCase` for the first one. Also helpful for if we ever want custom labels to be providable.

Tidied up a little as well, to be:

```
function iconProps() {
    return isAboveSmall
      ? {
          ...(navigationVariant === 'previous'
            ? { iconLeft: variantMap[navigationVariant].icon }
            : { iconRight: variantMap[navigationVariant].icon }),
          children: variantMap[navigationVariant].label,
        }
      : { icon: variantMap[navigationVariant].icon };
  }

  return (
    <li>
      <Button
        {...{
          css: navigationButtonStyle({
            inverted,
            navigationVariant,
          }),
          onClick: handleClick,
          inverted,
          disabled,
          variant: 'plain',
          'aria-label': variantMap[navigationVariant].ariaLabel,
          'data-testid': 'pagination-navigation',
          ...iconProps(),
        }}
      />
    </li>
  );
```

2022-12-23 17:03 UTC, blurbyte approved these changes
LGTM 🚀 

[santa](https://media.giphy.com/media/KLQ1lUzwovlkGds9Dy/giphy-downsized-large.gif)

2022-12-23 17:04 UTC, merged