[WF-714] Components documentation
datacamp/waffles pull request #134
Opened 2022-12-20 13:07 UTC by blurbyte

# Components documentation

## [WF-714](https://datacamp.atlassian.net/browse/WF-714)

## Changes

Complete documentation of the following components:

- ErrorBoundary
- Display
- Helpers
- Menu
- Portal
- Card
- ContentContainer
- Link
- Notification
- Resizable
- ScreenReaderOnly
- SideNavigation
- Slider
- Tabs
- Text
- Toast
- Chapeau

2022-12-20 16:53 UTC, ixTec requested changes
Lots of minor grammar/punctuation fixes, especially where we're missing "the" or "a" before a component name, along with:

- Some of the component header descriptions are worded towards _how_ a component should be used instead of _what_ a component actually is. I would look at `Asset` and `Code` do it for good examples of what we want
- Please can you update the tracker for these changes to show all in progress/completed etc

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/menu.mdx
> +It appears when the user interacts with a trigger, most commonly [Button](/components/button), although other elements can be used. Dropdown is placed next to the element that opened it. If it is in
most commonly _a_ Button

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/menu.mdx
> +It's option is defined with `Menu.Item` subcomponent. It can incude label text, description, left icon, right icon, active state, destructive variant, and small notification icon. Display item as `di
Reword to the following:

"Content is defined using the `Menu.Item` subcomponent. When an item can be used conditionally, but not currently, it should have the `disabled` prop  instead of being hidden or removed."

No need to list all of the props of Menu.Item, since we show them in the table below

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/menu.mdx
> +`Menu.Category` should be used to separate various `Menu.Items` into groups. It's divider can be hidden by providing `noDivider` prop.
_Its_

providing _the_ `noDivider` prop

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/menu.mdx
> +### Build
Not a fan of this subheading... Perhaps "Structure" would be more suited. Otherwise I think this can just been part of "Usage guidance" tbh

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/notification.mdx
> +By default `Notification` doesn't dismiss automatically. To make `Notification` dismissible, and to show a close button, provide `closable` prop.
provide _the_

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/notification.mdx
> +Custom follow-up actions, which should take the user to a page or flow related to the message itself, can be defined via `action` with `Notification.ActionButton` subcomponent. Clearly describe the a
with _the_ `Notification.ActionButton` subcomponent

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/notification.mdx
> +Show up in the task flow, to notify users of the status of an application. It usually appears at the start of the relevant content area or close to the section needing attention. It should be separat
Initial sentence needs rewording - not sure what we're trying to say with the first half

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/notification.mdx
> +Consigns an important system-wide message. It should be placed at the top of the page. It expands to fill the full width of the container.
I would use "Communicates" over "Consigns"

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/resizable.mdx
> +`Resizable` supports two orientations via `layout` prop: `row` and `column`.
via _the_

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/resizable.mdx
> +By default, panels are split equally, but their initial proportions could be customized by providing an array of `defaultProportions`. Keep in mind, that number of items in that array _must_ be equal
that _the_ number of items

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/resizable.mdx
> +    - for usability reasons, on mobile devices it is better to use regular static `flex` or `grid` layout
This doesn't make sense to be a discouraged thing.

Possible reword to something like:

- "use on mobile devices - instead use regular static `flex` or `grid` layout"

This may be important enough to put in a `Notification` instead

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/slider.mdx
> +When using `Slider` changes are reflected to a user immediately. It's ideal for adjusting settings such as volume. It shows the full range of available choices.
comma after `Slider`

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/slider.mdx
> +It is controlled by the `value` prop. It **always** must be an array. Depending on the provided `value`:
must always

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/slider.mdx
> +The minimal distance between values can be adjusted via `step` prop.
via _the_ `step` prop

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/tabs.mdx
> +<Layout title="Tabs" description="Organize related content, and let the user to navigate between groups of information, that appear within the same context.">
I would remove all commas in the description here.

and should be "and let the user ~~to~~ navigate"

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/text.mdx
> +It has already basic typography-related styles applied, such as `font-family`, `font-size`, and `font-weight`.
It has ~~already~~ basic

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +In general, toast is used to convey general confirmation that isn't critical, e.g. to inform the user that their recent action was successful. Each toast can come in one of the four variants: `info`,
component name needs to be capitalised / code snippet

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +### Build
Use "Structure" or remove sub heading completely

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +Toast dismisses automatically after a short time, but also can be dismissed by the user sooner. It's possible to configure custom timeout via `ToastProvider` globally or for individual toast within `
configure _a_ custom timeout

persist toasts by _setting the_

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +    - use for a non-critical single message, that is relevant at the moment
single non-critical

_in_ the moment

2022-12-20 16:53 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +    - go over 4 words for toast `title`
_use_ over

2022-12-21 12:45 UTC, blurbyte commented on doc-site/pages/components/card.mdx
> +    - use "Click Here" as a call to action label&mdash;it doesn't set up proper expectations of what's next
I think it is much more relevant in this context, and could be easily missed in general Button guidelines.

2022-12-21 12:46 UTC, blurbyte commented on doc-site/pages/components/chapeau.mdx
> +`Chapeau` provides extra context for the main [Heading](/components/heading) on the page, and usually describes the whole page category.
Yes, that's what I thought too.

2022-12-21 12:50 UTC, blurbyte commented on doc-site/pages/components/display.mdx
> +Use `Display` sparingly to create impact when the main goal is visual storytelling, and drawing user attention with typography. It does not have any sematic meaning and shouldn't be used as yet anoth
Actually I think example from BestPractices covers most common scenario, so probably nothing has to be added.

2022-12-21 13:00 UTC, blurbyte commented on doc-site/pages/components/helpers.mdx
Not really sure what exactly could be examples for missing helpers, since they don't really have any visual output.

2022-12-21 13:15 UTC, blurbyte commented on doc-site/pages/components/notification.mdx
> +Show up in the task flow, to notify users of the status of an application. It usually appears at the start of the relevant content area or close to the section needing attention. It should be separat
Removed first half.

2022-12-21 13:23 UTC, blurbyte commented on doc-site/pages/components/screen-reader-only.mdx
> +<Layout title="Screen Reader Only" description="Use when content has to be available to assistive technology, but otherwise hidden.">
Just swapped it with 1st sentence of Usage guidance section.

2022-12-21 13:27 UTC, blurbyte commented on doc-site/pages/components/side-navigation.mdx
> +<Layout title="Side Navigation" description="Standarizes and creates consistent navigation experience across DataCamp products.">
You mean what the component is rather why/how it should be used?

2022-12-21 13:32 UTC, blurbyte commented on doc-site/pages/components/toast.mdx
> +In general, toast is used to convey general confirmation that isn't critical, e.g. to inform the user that their recent action was successful. Each toast can come in one of the four variants: `info`,
There is no `Toast` component so not sure about it.

2022-12-22 15:18 UTC, ixTec requested changes

2022-12-22 15:18 UTC, ixTec commented on doc-site/pages/components/helpers.mdx
The examples don't necessary have to be visual-based, but I would do the following:

For `isHexColor` and `hexColorLuminance`, I would have a _very_ simple input that returns a visible result next to it of the entered value. 

For `deepChildrenMap`, this will be less visual but I'd just have small nested lists or something created from `deepMapChildren`, so that we have a clear code example that can be viewed

2022-12-22 15:18 UTC, ixTec commented on doc-site/pages/components/toast.mdx
> +In general, toast is used to convey general confirmation that isn't critical, e.g. to inform the user that their recent action was successful. Each toast can come in one of the four variants: `info`,
Oh yeah... 😆

2022-12-23 11:21 UTC, blurbyte commented on doc-site/pages/components/card.mdx
> +    - use "Click Here" as a call to action label&mdash;it doesn't set up proper expectations of what's next
Recommented: follow Button best practices for CTA.

2022-12-23 11:22 UTC, blurbyte commented on doc-site/pages/components/chapeau.mdx
> +`Chapeau` provides extra context for the main [Heading](/components/heading) on the page, and usually describes the whole page category.
Change to: 'Should be used alongside Heading, and usually describes the whole page category.'

2022-12-23 15:35 UTC, ixTec requested changes
Two _very_ minor changes until this is good imo

2022-12-23 15:35 UTC, ixTec commented on doc-site/examples/helpers/is-hex-color-basic-usage.tsx
> +      {...(!isHexColor(value) && { error: 'Incorrect value' })}
I would change this to "Not in hex notation" and "In hex notation" for some feedback to the viewer here

2022-12-23 15:35 UTC, ixTec commented on doc-site/examples/helpers/deep-children-map-basic-usage.tsx
> +        Notice how none of the components has <Code>inverted</Code> prop set
"have" not "has"

2022-12-23 16:28 UTC, blurbyte commented on doc-site/examples/helpers/is-hex-color-basic-usage.tsx
> +      {...(!isHexColor(value) && { error: 'Incorrect value' })}
Will update error message for now, we can tackle rest functionality later.

2022-12-23 16:49 UTC, ixTec approved these changes
![image](https://media3.giphy.com/media/3oKIPf3C7HqqYBVcCk/giphy.gif)

Approved 🥂

2022-12-23 16:54 UTC, merged