[WF-662] fix `setTitleCase` to not force-lowercase the “C” in “DataCamp” or force-uppercase the “i” in “iPhone”
datacamp/waffles pull request #139
Opened 2023-01-03 17:01 UTC by lensbart

# Fix `setTitleCase` to not force-lowercase the “C” in “DataCamp” or force-uppercase the “i” in “iPhone”

## [WF-662](https://datacamp.atlassian.net/browse/WF-662)

## Changes

### 🔧 Minor Changes

- This PR changes the capitalisation behaviour for button text. With these changes, already-capitalised words (e.g. `iPhone`, `SQL`, `DataCamp`, `GitHub`, etc.) will remain intact, provided that they don’t appear in the list of stop words. Previously, they were changed to respectively `Iphone`, `Sql`, `Datacamp` and `Github`.

WF-662 contained two items: the fix made in this PR, and a suggestion to decrease the amount of stop words so as to conform to an existing (or more widely used) style guide. Because of this suggestion, the ticket was moved to the backlog. Without a change in stop words, I’m assuming that the behaviour of `setTitleCase` can already be improved. (For context: at Workspace, we have 5 instances of `setTitleCase` that were introduced to offset this bug.)

2023-01-04 13:59 UTC, ixTec requested changes
A nice solution for handling mixed case words. We may want to approach this differently (perhaps with configuration) in the future, as words "liKE tHIS" will be left as is (which would be undesired).  I don't think this is something we need to address now though.

Besides the few inline comments I've added, I think we should also update the documentation example for this (`doc-site/examples/helpers/set-title-case-basic-usage.tsx`), to include some mixed case words. Maybe some copy like "Download DataCamp for Mobile today. Available on iPhone and Android"

2023-01-04 13:59 UTC, ixTec commented on src/helpers/set-title-case.ts
> +function hasUppercase(text: string) {
Let's add a single line comment here for what it's for

2023-01-04 13:59 UTC, ixTec commented on src/helpers/set-title-case.ts
>   * Convert string content into Title Case
We likely want to extend this comment to reflect the change that mixed case words will be respected / left unchanged

2023-01-04 14:03 UTC, lensbart commented on src/helpers/set-title-case.ts
> +function hasUppercase(text: string) {
“Mixed case” would imply the presence of both lowercase and uppercase characters, whereas this function only reports `true` if it encounters the presence of uppercase characters.

I found the name of this function to be sufficiently self-explanatory, but happy to add a comment. Is the inclusion of a comment per function always desired? Then ideally this would be reflected in `CODING_STYLE.md`.

2023-01-04 14:06 UTC, ixTec commented on src/helpers/set-title-case.ts
> +  for (let index = 0; index < text.length; index += 1) {
`index += 1` can be shortened to `index++` notation

2023-01-04 14:10 UTC, ixTec commented on src/helpers/set-title-case.ts
> +function hasUppercase(text: string) {
You're right, that's my bad. I think `containsUppercase` or `includesUppercase` would be more suitable here though.

For comments, it's just something we tend to do for our helper / hook utils - not across the rest of the repo

2023-01-04 14:17 UTC, lensbart commented
> words "liKE tHIS" will be left as is (which would be undesired)

@ixTec I think it will be impossible to police against this, and we should trust the developer here. (It is very unlikely that anyone would write something like this by mistake, or without good reason.)

2023-01-05 10:00 UTC, ixTec approved these changes

2023-01-05 16:47 UTC, merged