[WF-777] Tag Component
datacamp/waffles pull request #154
Opened 2023-02-13 16:03 UTC by ixTec

# Added new Tag component

## [WF-777](https://datacamp.atlassian.net/browse/WF-777)

## Changes

### 🚀 Major Changes

- New `Tag` component available

### ❓ Misc Changes

- Updated `Badge` usage guidance to reflect new addition of Tag component

## Screenshot(s):
![Screenshot 2023-02-13 at 16 03 43](https://user-images.githubusercontent.com/9938773/218509146-45083153-2619-432d-a5cc-1494cf991e9b.png)

2023-02-14 12:31 UTC, blurbyte requested changes
Looks really good overall. Really good docs, distinction between Tag and Badge should be pretty clear.

Visually I think the fact that when hovering over X whole Tag is highlighted feels a bit awkward to me (focus is fine). For small Tag of course there is no way around it since hitbox is so small but for medium maybe only close button should have this hover style?

Close X for both sizes feels a bit too small.

Was thinking a bit more about API. Imho there is no real practical distinction between `onClick` and `onClose`, besides the part of element which is firing this event. Maybe it will be better to merge it into 1 handler called for example `onInteraction`. That way I think we can change `mode` into simple `closable` flag (to keep it more in line with Notification). Ideally probably `closable` should be default but `nonClosable` might be a bit weird. Also should help simplifying typings a bit. Or we can leave mode as it is to make difference between use cases a bit more apparent.

For whatever reason mode is described as string in docs (might be irrelevant if we proceed with changes above):
<img width="853" alt="Screenshot 2023-02-14 at 13 24 23" src="https://user-images.githubusercontent.com/20565536/218739673-f5cdaa82-f731-46db-8643-be7863ad8b20.png">

2023-02-14 12:31 UTC, blurbyte commented on src/tag/__tests__/tag-closable.story.tsx
> +function Story() {
I would maybe improve this example slightly to be more 'realistic'. We can put variants as initial state and remove appropriate one when tag is closed. That way good practice of keeping UI as a function of the state will be presented.

2023-02-14 12:31 UTC, blurbyte commented on src/tag/__tests__/tag.e2e.ts
> +describe('Tag', () => {
I would add test for focus style of interactive / closable tag.

2023-02-14 12:31 UTC, blurbyte commented on src/tag/close-button.tsx
> +  function renderCloseIcon() {
For clarity I would put it as a separate `CloseIcon` component (in this folder).

2023-02-14 12:31 UTC, blurbyte commented on src/tag/close-button.tsx
> +    width: '12',
Because it's square would make sense to call it size / sizing and put as width / height.

2023-02-15 12:58 UTC, blurbyte requested changes
We are super close to finishing it, really love how it looks and behaves.

Noticed there is no hover color change for 'navy' variant (should be lighter). Also I think we are missing some guidelines on capitalization of tag's label.

2023-02-15 12:58 UTC, blurbyte commented on src/tag/tag-internal.tsx
> +      : '';
Probably should be _null_ instead of empty string.

2023-02-15 13:19 UTC, ixTec commented
Updated hover styling for navy variant. Not sure we can specify any guidelines for content capitalisation and it's very dependent on what the content is

2023-02-15 13:23 UTC, blurbyte approved these changes
Looks good, let's merge 🚀

2023-02-15 13:50 UTC, merged