[WF-582] Update sizing for buttons, inputs and formfields
datacamp/waffles pull request #35
Opened 2022-05-25 10:46 UTC by ixTec

# Update sizing for buttons, inputs and formfields

## [WF-582](https://datacamp.atlassian.net/browse/WF-582)

## Changes

### 🚀 Major Changes

- Added new `fontSizes.xsmall` token with `10px` value
- `sizing.small` token now has a value of `28px` (was `24px`)

### 🔧 Minor Changes

- small` variant `Button`, `FormField` and `Input` components now use  `fontSizes.small` (was `fontSizes.medium`)
    - These variants will also now use `small` icons by default (was `medium`)
    - `medium` and `large` variants are unaffected

2022-05-30 09:03 UTC, blurbyte commented on src/button/button-internal.tsx
> +    return originalIcon.props['size']
I think dot could be used safely here.

2022-05-30 09:03 UTC, blurbyte commented on src/button/button-internal.tsx
> +          // Handle large buttons having medium sized icons by default
Maybe mentioned medium and small sizes being passed as it is.

2022-05-30 09:15 UTC, blurbyte commented on src/input/input-internal.tsx
> +          {cloneIconElement(iconLeft as React.ReactElement)}
I think in similar way to `Button` we can safely change `iconLeft` and `enhancerRight` type to `JSX.Element`, since realistically we want only 1 element to be passed.

2022-05-30 09:17 UTC, blurbyte commented on src/input/input-internal.tsx
>            {Children.map(enhancerRight, (child) => {
With `enhancerRight` both _Children.map_ nor _isValidElement_ won't be required anymore.

2022-05-30 09:18 UTC, blurbyte commented on src/input/input-internal.tsx
> +  function cloneIconElement(
Tbh I think in this case duplication is fine (it's only 1 line of code if put inside `render` functions), so no need for this utility function. You can just assign `const iconSize = size === 'large' ? 'medium' : size` somewhere at the top of component.

2022-05-30 09:22 UTC, blurbyte commented on src/form-field/form-field.tsx
> +    size: size,
No need to write `size: size`, `size` alone is enough.

2022-05-30 09:48 UTC, ixTec commented on src/input/input-internal.tsx
> +  function cloneIconElement(
This is used in three places within `input-internal` and handles the different use cases. Using a declaration of `iconSize` won't work as the icons could (in theory) have different sizes

2022-05-30 09:50 UTC, ixTec commented on src/button/button-internal.tsx
> +    return originalIcon.props['size']
`.props` isn't an explicitly typed object for the icon, so we'd have to tell typescript to ignore it, which should be avoided where possible

2022-05-30 11:28 UTC, blurbyte commented on src/input/input-internal.tsx
> +  function cloneIconElement(
I was thinking: since it's just 1 liner for iconLeft and enhancerRight `iconLeft.props.size ? cloneElement(iconLeft, { inverted }) : cloneElement(iconLeft, { inverted, size: iconSize })` it might be overkill to provided it via separate function.

2022-05-30 14:19 UTC, ixTec commented on src/input/input-internal.tsx
> +  function cloneIconElement(
I think for code readability, it makes sense to keep this as a separate function here

2022-05-31 12:05 UTC, blurbyte requested changes
We are pretty close. A few minor things:

- Probably it's good idea to add snapshot of each size for `FormField`
- I would test all sizes in `stories/form-field-label`

Also I think it would make sense to add `small` TextArea but we need design spec for it from Petra first.

2022-06-01 07:03 UTC, blurbyte approved these changes
Looks good! 

Just a few really minor things:

- for that bookmarkStyle I think `vertical-align: baseline` works the best
- casing in FormField sizes example for labels seems to be off (title casing, tbh I'm not 100% sure which is correct, probably we are missing guidelines for that, but right now regular sentence case is used everywhere else)
- I think side padding in TextArea small should be smaller to be consistent with small input, ~but waiting for this one for Petra to be confirmed (we can update it in some PR later)~

Be free to merge otherwise 🚀

2022-06-01 11:23 UTC, merged