[WF-546] Menu
datacamp/waffles pull request #36
Opened 2022-05-25 11:46 UTC by blurbyte

# New Menu dropdown component

## [WF-567](https://datacamp.atlassian.net/browse/WF-567)

## Changes

### 🚀 Major Changes

- Added new `Menu` component
    - It has regular and inverted version
    - Placement is configurable
    - Ships with accessible `Menu.Item` and `Menu.Button` subcomponents; Radio and Checkbox planned
    - `useMenu` hook exposes some internal `Menu` data
    - ⚠️ There is issue with a11y when custom styles are provided with `css` prop to `Menu` subcomponents; most likely will address it with making it required to wrap these subcomponents with `Menu.Category` (which is mentioned in docs even right now)
    - `SideNavigation.Item` is very similar to `Menu.Item`; probably should have `label` instead of `children`, but will tackle it next release

### 🔧 Minor Changes

- Added `xxsmall` (10px) font size design token
- Added `deepChildrenMap` helper
- Updated `Tooltip` internals
- Updated `Portal` component and how it is used internally, so it works better with refs
- Updated the size of `SideNavigation` category label on desktop to use new font size token
- Tighten up some TS typings

### ❓ Misc Changes

- Updated roadmap with what we discussed in Belgium
- Bumped some dependencies

## Screenshot(s)

Regular menu with all features enabled:
<img width="320" alt="Screenshot 2022-05-25 at 13 39 56" src="https://user-images.githubusercontent.com/20565536/170254064-7f044f84-526a-4922-8465-0207c1e610e9.png">

Inverted menu:
<img width="351" alt="Screenshot 2022-05-25 at 13 40 44" src="https://user-images.githubusercontent.com/20565536/170254089-49dbbc15-a36f-40be-8bae-6f4f7f63dbf6.png">

2022-05-25 14:12 UTC, ixTec requested changes

2022-05-25 14:12 UTC, ixTec commented on src/menu/category.tsx
> +  noDivider = false,
I think we should change this to `hasDivider` and default to false. Right now, if you have a category as your first child under `Menu`, you have to manually disable the divider for it to look right in a default configuration.

For further siblings, having a label at the very least looks visually okay and so a horizontal divider only further improves it there but I think having it as opt-in rather than opt-out would be a better approach

2022-05-25 14:12 UTC, ixTec commented on src/menu/item.tsx
> +  showAlert?: boolean;
I think `showNotificationDot` or `hasNotificationDot` is a better term for this prop

2022-05-25 14:25 UTC, blurbyte commented on doc-site/pages/components/menu.mdx
> +### useMenu
Yeah, something to think about. Because for hooks you can:
1. Provide config for hook itself
2. It also returns some data
For now I would leave as it is, since this particular hook is not that critical (aka is 100% optional to use, not like in e.g. Toast where it is core functionality). We can improve it along with Petra's docs reimagination.

2022-05-25 14:42 UTC, blurbyte commented on src/menu/item.tsx
> +  showAlert?: boolean;
Makes sense, I will change it to `showNotificationDot`.

2022-05-25 15:07 UTC, blurbyte commented on src/menu/category.tsx
> +  noDivider = false,
Something to think about. I used the same prop as in `SideNavigation.Category`. So would make sense to update it there as well. Also I think it would make sense to change how `SideNavigation.Item` content is provided (right now via `children` but probably makes sense to do it via `label` prop). That's 2 breaking changes. Let's push it to the next release.

2022-05-26 08:37 UTC, ixTec commented on src/menu/notification-dot.tsx
> +import { alertDotStyle } from './styles';
`alertDotStyle` should be renamed to match `notificationDot`

2022-05-26 08:38 UTC, ixTec commented on src/menu/styles.ts
> +export function alertDotStyle() {
`alertDotStyle` should be renamed to match `notificationDot`

2022-05-26 10:13 UTC, ixTec approved these changes

2022-05-26 11:39 UTC, merged