[WF-593] Avatar Component
datacamp/waffles pull request #49
Opened 2022-06-09 11:49 UTC by ixTec

# New Avatar component

## [WF-593](https://datacamp.atlassian.net/browse/WF-593)

## Changes

### 🚀 Major Changes

- New `Avatar` component
    - Configurable with `variant` and `size` properties
        - `variant` colours match `Badge` component
    - Has `contentFill` prop to control whether the content fills the avatar space or restricts itself to the predefined spacing at each size

### ❓ Misc Changes

- Updated how the docs-site resolves union types containing generics

## Screenshot(s):

![Screenshot 2022-06-09 at 12 40 33](https://user-images.githubusercontent.com/9938773/172838362-ba51c187-7aac-4750-9425-bd99b88f63fc.png)
![Screenshot 2022-06-09 at 12 41 00](https://user-images.githubusercontent.com/9938773/172838436-8ac7489a-b825-4aca-b179-e0c4452965bc.png)
![Screenshot 2022-06-09 at 12 41 14](https://user-images.githubusercontent.com/9938773/172838470-5524976f-7f27-427f-be62-057a24e62a67.png)

2022-06-09 14:56 UTC, blurbyte requested changes
Amazing job. API seems very simple and straightforward to use (yet quite flexible) 🥇.

I would just introduce a little change to make it more resilient: when it's a string just take first character.

## For docs:

- Would rename _string_ to _text_ (string feels too technical)
- I think only one content type is enough here (and remove string content)
- For each subsection use `<Heading size="medium">`
- Would rename `profile-pic-placeholder.png` to `profile-pic-example.png`

Also noticed on mobile it's a bit broken:
<img width="387" alt="Screenshot 2022-06-09 at 16 28 23" src="https://user-images.githubusercontent.com/20565536/172872959-7e0d0670-be2c-4c89-ac3d-d3115fa1122a.png">
Probably setting `flex-shrink: 0` on wrappers should be enough (and `flex-wrap: wrap` for examples wrapper).

## For tests

### Unit
There is a way to handle static assets in jest: https://stephencharlesweiss.com/jest-handling-static-assets-mocks. That way you don't have to leave src empty.

In unit test snapshots I would mock `DataCampBrand` since it is polluting snapshots with bulk of redundant info:
```
jest.mock('../../path-to-data-camp-brand', () => 'DataCampBrand')
```
(or something similar, might be necessary to wrap it with div or sth).

### Stories

In cypress tests image is broken (probably have to put example PNG in public of workbench, since under the hood workbench is used to run these tests).

Would add some `gap` between each component so they don't touch each other.

For variant again I think it is enough to use only one content type.

Would write separate story for each content type (Text, Icon, Asset & Image).

2022-06-09 14:56 UTC, blurbyte commented on src/avatar/avatar.tsx
> +  if (typeof content === 'string' && content.length > 1) {
Tbh to make it resilient I would just take the first letter of a string and capitalize it (so warning won't be necessary). Of course in docs we still mention that ideally 1 character should be provided.

2022-06-09 14:56 UTC, blurbyte commented on doc-site/pages/components/avatar.mdx
> +<Example title="Fill Content Space" path="avatar/content-fill">
Maybe 'Fill Whole Avatar Space'?

2022-06-09 14:56 UTC, blurbyte commented on src/avatar/styles.ts
> +export function avatarWrapperStyle({ size, variant }: AvatarWrapperProps) {
I think it could be called `avatarStyle`.

2022-06-09 14:56 UTC, blurbyte commented on src/avatar/styles.ts
> +export function avatarContentWrapperStyle({
Maybe `avatarContent`?

2022-06-09 14:56 UTC, blurbyte commented on src/avatar/styles.ts
> +type AvatarContentWrapperProps = {
As per convention `...StyleOptions`.

2022-06-10 11:26 UTC, blurbyte requested changes
Great job. Just a few small tweaks.
Just noticed texts size in status table of 'Unavialable' should be updated after button change:
<img width="748" alt="Screenshot 2022-06-10 at 13 03 39" src="https://user-images.githubusercontent.com/20565536/173055214-7490bf0c-5ff4-4199-8acc-3341a1e70f8b.png">

2022-06-10 11:26 UTC, blurbyte commented on doc-site/examples/avatar/content-fill.tsx
> +      <Heading as="h4" size="medium">
You don't have to specify `as` here, `medium` defaults to `h4`.

2022-06-10 11:26 UTC, blurbyte commented on doc-site/examples/avatar/sizes.tsx
> +        css={css`
Maybe define `wrapperStyle` at the top. It's used 3 times (and clear margin in the last one).

2022-06-10 11:26 UTC, blurbyte commented on doc-site/pages/overview/roadmap.mdx
> -| Avatar                      | Standarized way to display images in a circle.                                                        | Q2&nbsp;2022     |
I think we can remove question mark from 'Making it Work for Marketing' since it will happen next Q for sure.

2022-06-10 11:26 UTC, blurbyte commented on doc-site/pages/overview/roadmap.mdx
> +  <ComponentStatus
Let's add `Card` and `ResizableElement` to the list, both as unavailable.

2022-06-10 11:26 UTC, blurbyte commented on jest.config.js
> +      require.resolve('./jest/image-file-mock.js'),
Maybe let's create `test-setup` dir in the root, and put there `test-setup.ts` (could be `setup` or `initial-setup`) and this file there.

2022-06-10 11:26 UTC, blurbyte commented on src/avatar/__tests__/avatar.spec.tsx
> +import { render } from '@testing-library/react';
I think the use case where some longer string is provided and the only first char is left should be tested.

2022-06-10 11:26 UTC, blurbyte commented on src/avatar/avatar.tsx
> +          ? (content as string).charAt(0).toUpperCase()
TS is smart enough to figure it out, no need to cast it.

2022-06-10 11:26 UTC, blurbyte commented on src/avatar/__tests__/avatar.spec.tsx
> +            <>
It should be wrapped in `<div>`. When you're doing `container.firstChild` it grabs only `Avatar` with text content.

2022-06-10 11:26 UTC, blurbyte commented on src/avatar/__tests__/avatar.spec.tsx
> +              <Avatar variant={variant} size={size} content={<GitLogomark />} />
Do we need this one? If yes please mock it in similar way to DCBrand.

2022-06-10 12:31 UTC, ixTec commented on jest.config.js
> +      require.resolve('./jest/image-file-mock.js'),
Little confused by this comment - can you expand please?

2022-06-10 13:35 UTC, merged