[WF-538] Empty State Component
datacamp/waffles pull request #55
Opened 2022-06-23 14:27 UTC by ixTec

# Empty State Component

## [WF-538](https://datacamp.atlassian.net/browse/WF-538)

## Changes

### 🚀 Major Changes

- Added new `EmptyState` component
    - Has the following children:  `EmptyState.List`, `EmptyState.ListItem` and `EmptyState.Content.
    - Can set row or column layout via `direction` property
    - Can be inverted using `inverted` property
    - Heading is set via `title` property

## Screenshot(s):

![Screenshot 2022-06-23 at 15 24 46](https://user-images.githubusercontent.com/9938773/175322874-0a6c6676-9b3b-4f0f-a33d-d9a8d92b4b0c.png)
![Screenshot 2022-06-23 at 15 25 11](https://user-images.githubusercontent.com/9938773/175322979-3c3ed814-bf16-47ac-bf4d-4409f3545595.png)

2022-06-23 14:28 UTC, ixTec commented
**Things to consider:**

- Using name `direction` for property to be similar to the vanilla `flex-direction` css property
- We may want `title` prop to be type `JSX.Element` instead of `string`, to support configuration of level?

2022-06-24 11:52 UTC, blurbyte commented
I wold change `direction` to orientation (vertical / horizontal).
I think wouldn't hurt if `title` will be `React.ReactNode`.
Don't think we need `EmptyState.Content` wrapper.

2022-07-06 12:05 UTC, blurbyte requested changes
Looks really good 🥇.

A few random comments (apart what is inline):

1. I would definitely NOT use 'Lorem ipsum...' in examples (for tests it's fine). Some of the samples from Petra's inventory research could be used here.

2. Also we may show an example (don't have to separate section, just change one of existing ones):
    - without `List` at all
    - `ListItem`s without icons

3. Looks like TS stop picking up `src` dir after my last jest config adjustments. I think we have to update `include` field in root `tsconfig.json` to ` "include": ["src", "test-setup/initial-setup.ts"]`.

2022-07-06 12:14 UTC, blurbyte commented on src/empty-state/list-item.tsx
> +function ListItem({ icon, children, ...restProps }: ListItemProps) {
I would use `<Text as="li">` under the hood since it bakes in a lot of font-specific styling.

2022-07-06 12:15 UTC, ixTec commented on src/empty-state/empty-state-internal.tsx
> +  title?: React.ReactNode;
Specified as optional because Petra wanted it configurable, since sometimes a title won't be provided

2022-07-06 12:15 UTC, ixTec commented on src/empty-state/empty-state-internal.tsx
> +  image?: JSX.Element;
Specified as optional because Petra wanted it configurable, since sometimes an image won't be provided in all use cases

2022-07-06 12:16 UTC, ixTec commented on src/empty-state/empty-state-internal.tsx
> +          <Heading css={headingStyle} size={'xlarge'} inverted={inverted}>
This is already `xlarge` ?

2022-07-06 12:18 UTC, ixTec commented on src/empty-state/list-item.tsx
> +  icon?: JSX.Element;
I think sticking to more generalised terms for props is better. This is _the icon_ for the list item, and makes no sense to use `leftIcon` without a matching `rightIcon`

2022-07-07 10:52 UTC, blurbyte requested changes
A few additional improvements could be made.

2022-07-07 10:52 UTC, blurbyte commented on src/empty-state/styles.ts
> +function emptyStateBaseStyle() {
This one actually don't have to be func (only used internally) so it can be used later as `${emptyStateBaseStyle}`.

2022-07-07 10:52 UTC, blurbyte commented on src/empty-state/styles.ts
> +    flex-direction: column;
These 2 lines could be omitted, so button won't span full width of container, which is a bit too heavy visually:
<img width="673" alt="Screenshot 2022-07-07 at 12 33 23" src="https://user-images.githubusercontent.com/20565536/177754553-ac4bfbc4-7b27-404b-bc3d-a1ac24c3731f.png">

2022-07-07 10:52 UTC, blurbyte commented on src/empty-state/styles.ts
> +    font-size: ${tokens.fontSizes.medium};
Don't think we need it anymore since List has font styles encapsulated and the previous content wrapper is no longer used (regular Paragraph is used instead).

2022-07-07 10:52 UTC, blurbyte commented on src/empty-state/styles.ts
> +    border-width: 1px;
Token can be used here `tokens.borderWidth.thin`.

2022-07-07 10:52 UTC, blurbyte commented on src/empty-state/styles.ts
> +    list-style: none;
If there is no custom icon provided for `ListItem` we should render default disc. Right now it's kind of hard to tell if it's a list:
<img width="352" alt="Screenshot 2022-07-07 at 12 33 34" src="https://user-images.githubusercontent.com/20565536/177756223-33095826-95ba-47ec-8e90-bb5c872cba5d.png">

In this case padding left `tokens.spacing.large` looks good. Also `display: flex` will have to be disabled or disc won't render.

2022-07-08 14:43 UTC, blurbyte requested changes
Just a few minor changes.

2022-07-08 14:43 UTC, blurbyte commented on src/empty-state/styles.ts
> +    list-style: ${hasIcon ? 'none' : 'inside'};
It looks pretty bad with `list-style: inside` if the content is long:
<img width="498" alt="Screenshot 2022-07-08 at 16 34 50" src="https://user-images.githubusercontent.com/20565536/178013643-2b8f07ce-8fdb-41b2-99cd-84122c125d29.png">

I would change it to `outside` and add some `margin-left`. Either `tokens.spacing.large` if we want to keep nice indentation or `tokens.spacing.xlarge` if we want a text to be aligned for version with and without icon (not sure if they should/will be mixed at all).

2022-07-08 14:43 UTC, blurbyte commented on doc-site/pages/components/empty-state.mdx
> +<Example title="Centered Column" path="empty-state/centered-column">
'Centered' should be enough. Example file name could be changed to `centered.tsx` too.

2022-07-08 14:43 UTC, blurbyte commented on doc-site/examples/empty-state/centered-column.tsx
> +      <Paragraph>
Maybe add some custom larger bottom margin here.

2022-07-08 14:43 UTC, blurbyte commented on doc-site/examples/empty-state/inverted.tsx
> +      <Paragraph>
This paragraph could be removed.

2022-07-08 15:03 UTC, ixTec commented on doc-site/pages/components/empty-state.mdx
> +<Example title="Centered Column" path="empty-state/centered-column">
Going to rename it to `Vertical Centered` just to make it clear that this is the only use case for centered

2022-07-11 10:33 UTC, blurbyte requested changes
Looks really good, just 1 small change to `ListItem` and we are good to go.

2022-07-11 10:33 UTC, blurbyte commented on src/empty-state/styles.ts
> +    margin-left: ${hasIcon ? '0' : '16px'};
It still looks a bit weird. I would go with `margin-left: ${tokens.spacing.large}` or `margin-left: ${tokens.spacing.xlarge}` with `padding-left: 0;` when there is no icon. Spacing `large` looks better but spacing `xlarge` makes variants with/without icon text aligned (prolly we can ask Petra for feedback about it).

2022-07-11 13:07 UTC, blurbyte approved these changes
Let's merge 🚀.

2022-07-11 13:10 UTC, merged