Small Menu and Dialog improvements
datacamp/waffles pull request #60
Opened 2022-07-14 13:31 UTC by blurbyte

# Small Menu and Dialog improvements

## Changes

### 🚀 Major Changes

- Added `destructive` variant to `Menu.Item`.

### 🔧 Minor Changes

- Updated the default alignment of buttons in `Dialog` and `Drawer` footers (so they are set apart instead close together).

### ❓ Misc Changes

- Reverted changes of custom Jest setup. Unfortunately it was breaking Cypress typings.
-  Bumped _emotion_ and _floting-ui_ deps versions.
- Updated main background color of docs based on updated specs.

## Screenshot(s):
<img width="390" alt="Screenshot 2022-07-14 at 15 30 38" src="https://user-images.githubusercontent.com/20565536/178994242-99694f26-9de4-4a67-bf80-8c2f24db799b.png">
<img width="668" alt="Screenshot 2022-07-14 at 15 31 08" src="https://user-images.githubusercontent.com/20565536/178994264-e4ff111a-24df-43a5-955e-e1d30c511f30.png">

2022-07-14 14:25 UTC, ixTec requested changes
Few minor comments, with the primary one being the dialog button wrapping

2022-07-14 14:25 UTC, ixTec commented on doc-site/pages/overview/roadmap.mdx
> +_Last updated on 14 June 2022._
Should be July

2022-07-14 14:25 UTC, ixTec commented on doc-site/examples/dialog/playground-config.ts
> +          <div>
On very small screen widths, the buttons in this div begin to wrap. We should add some styling in this playground to clean up how they look in this case.

On top of this, there is no wrapping behaviour for the footer, and so content is overflowing if it's too large. We should probably address this too
![Screenshot 2022-07-14 at 15 13 50](https://user-images.githubusercontent.com/9938773/179003273-e553a820-949d-44d6-8c05-8826f00115a9.png)

2022-07-14 14:25 UTC, ixTec commented on src/menu/styles.ts
> +    hoverColor: hexToRgba(tokens.colors.white, tokens.opacity.low),
I would rename `hoverColor` / `activeColor `to better imply they're intended for backgroundColor use. I'm also unsure behind the naming of `activeColor` currently

2022-07-14 14:54 UTC, blurbyte commented on doc-site/examples/dialog/playground-config.ts
> +          <div>
Good catch.

2022-07-15 09:29 UTC, ixTec approved these changes
Let's mergeeee 🚀

2022-07-15 11:21 UTC, merged