[WF-603] Resizable
datacamp/waffles pull request #66
Opened 2022-07-22 10:53 UTC by blurbyte

# Resizable component

## [WF-603](https://datacamp.atlassian.net/browse/WF-603)

## Changes

children,
  orientation = 'vertical',
  initialProportions,
  minSubsectionSize = '100px',
  showSeparators = false,
  inverted = false,
  onResizeStart,
  onResizeEnd,

### 🚀 Major Changes

Implemented `Resizable` component: it renders its children separated by draggable dividers, so the width or height (depending on orientation) could be adjusted

Its orientation could be changed (vertical / horizontal) and initial proportions could be set (otherwise subsections are split equally). Minimum size of subsection could be set, and subsection can't be collapsed below this value.

It's possible to show / hide separators depending on the situation.

TODO: How onResizeEnd is handled is not ideal (it's called in useEffect which could cause memory leak), but it works.

**Questions**
- What is better name: _divider_ or _separator_ (`showSeparators` prop)
- Is `minSubsectionSize` clear enough? Maybe there is better name for _subsection_?

## Screenshot(s):

Nested layout example:
<img width="685" alt="resizable-example" src="https://user-images.githubusercontent.com/20565536/180423628-e61da4e2-c681-43ab-866d-05509377ade7.png">

Recording:
https://user-images.githubusercontent.com/20565536/180423674-1872edf6-4e6f-4b66-976b-dbdefc8e09ad.mp4

2022-07-22 14:50 UTC, ixTec requested changes
Some very creative solutions to tricky problems here, nice!

Added several comments to the code, but also some overall points too:

**Answers to questions:**
- I'm leaning towards `divider` as a term, so `showDividers`. etc
- In regards to `minSubsectionSize`, I think the documentation should mention it's width vs height depending on orientation. I think also something can only be a "subsection" if it's a child of another subsection, so I think "section" is enough. Likely `minSize` is enough here too though.

**Misc comments/feedback:**
- In regards to terminology, I am not keen on the "subsection"/"section" use. I think one of the following may be more suitable: "segment" or "panel" - what do you think?
- Would we benefit from a 'maxSize' prop also?
- I would rename `initialProportions` to `defaultSizes`
- There is quite a large issue when resizing the browser window (and thus changing the size of the resizable container). It does not update measurements of sections correctly. Happy to demonstrate this if needed
- I think there's some room for confusion over the `orientation` and how it impacts the layout. "Vertical" `orientation` splits the component into columns (and so across the container), but horizontal `orientation` splits it into rows, down the container ? Perhaps we need to reconsider this, especially if we compare to something like empty-state
- Looks like some of the types in the props table aren't resolving correctly (e.g. `children`)
- The labels used within the doc examples seem a bit mixed up. Some "First Second Subsection" and lots of "First Resizable Subsection" duplication in examples. Also, some should probably be "Section" vs "Subsection"

I still more comments to come next week on the actual component implementation

2022-07-22 14:50 UTC, ixTec commented on src/resizable/constants.ts
> +export const KEYBOARD_STEP = 10;
I think we may want these configurable by the consumer?
Especially  `DIVIDER_HITBOX_SIZE` or `DIVIDER_HITBOX_SIZE`

2022-07-22 14:50 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* The elements to render in subsections, divided by separator. At lest 2 must be provided. */
"... Must provide at least 2 (two) elements."

2022-07-22 14:50 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* The minimal size of the subsection. Default is `100px`. */
Change to "The minimum size..."

2022-07-22 14:50 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* An array of proportions, e.g. `[2, 1, 1]`, which determine initial size of each subsection. Must have the same length as the number of provided elements. When not provided the subsections will d
"... which determine the default relative size of each section. ..."

2022-07-22 14:50 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* Handler called when separator just started to move. */
Can change comment to:
"Called when divider begins to move."

2022-07-22 14:50 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* Handler called when separator just stopped moving. Useful for retreiving subsections proportions after resizing via `proportions` argument. For example could be used to persist proportions in lo
Think we can remove the "for example..." bit and update this comment to be:

"Called when divider stops moving. Useful for retrieving the proportions of sections." I don't think it's currently clear what the `proportions` argument is here

2022-07-22 14:50 UTC, ixTec commented on src/resizable/subsection.tsx
> +  // It prevents emotion from appling new class each time a new value is provided
"applying"

2022-07-25 08:26 UTC, blurbyte commented
Great review, a lot of good points. Based on feedback I'm planning to:

- Rename Separator -> Divider
- Reame Subsection -> Panel
- I think `initialProportions` better reflect, what it actually does; I feel `defaultSizes` kind of implies you want to provide sizes in pixels
- Good catch about not handling browser window resize - in this case proportions should be preserved
- About `orientation`: `row` / `column` is a possibility here for sure
- Children are `JSX.Element[]` so its technically `arrayType`

Something for future releases:

- `maxSize`

2022-07-25 09:33 UTC, blurbyte commented on src/resizable/constants.ts
> +export const KEYBOARD_STEP = 10;
Yeah, something to consider for future releases, maybe even providing custom divider component. But overall it should be rather rare use case. In general we want all resizables to look the same.

2022-07-25 11:15 UTC, blurbyte commented on doc-site/examples/resizable/playground-config.tsx
> +        width: '100%',
That's what I tried at first, but turns out emotion was going crazy and applied new class each time value changed when dragging, which you can imagine affected performance by a lot (made it laggy).

2022-07-25 11:16 UTC, blurbyte commented on doc-site/examples/resizable/playground-config.tsx
> +        width: '100%',
For some reason emotion is not working in playground so have to use regular `style`.

2022-07-25 11:16 UTC, blurbyte commented on doc-site/examples/resizable/playground-config.tsx
> +        borderRadius: '4px',
Will check it, not 100% sure if will work in playground.

2022-07-26 11:10 UTC, ixTec requested changes
Looking much better!

- Uses of `subsection` should be updated to be `panel`
- Uses of `separator` should be updated to be `divider`
- There's some funky behaviour around resizing after resizing another one. It's almost like it allows you resize beyond the original min size? (see attached video
- Previously discussed resize behaviour

https://user-images.githubusercontent.com/9938773/180987499-5b9b1f14-e2f8-4c9f-afc4-d8cb81cf12d1.mov

2022-07-26 12:10 UTC, blurbyte commented on src/resizable/resizable.tsx
> +            let minDividerPosition = 0;
Really good suggestion, makes it much more readable.

2022-07-26 13:10 UTC, ixTec requested changes
I really like the advanced usage example! Nice one.

Approved with some minor changes required before merge (some could be put into the refinement ticket):

- Missing import inside playground example
- `minSize` prop description should mention that this value should be specified in pixels
- If a `minSize` value is provided that is larger than the width of the component, it does not look good :D

2022-07-26 13:10 UTC, ixTec commented on doc-site/examples/resizable/playground-config.tsx
> +import { Paragraph } from '@datacamp/waffles/paragraph';
tokens should be included as an import in the initial code for the example

2022-07-26 13:10 UTC, ixTec commented on src/resizable/resizable.tsx
> +  /* The minimum size of the panel. When resizing, panel can't be collapsed below this value. Default is `100px`. */
Should mention that this value should be specified only in pixels

2022-07-26 14:11 UTC, merged