[WF-551] Add `isLoading` state to button
datacamp/waffles pull request #69
Opened 2022-07-28 13:55 UTC by ixTec

# Add `isLoading` state prop to button

## [WF-551](https://datacamp.atlassian.net/browse/WF-551)

## Changes

### 🚀 Major Changes

- Add new `isLoading` prop for button component

### ❓ Misc Changes

- Fix a couple of minor errors

## Screenshot(s):
![Screenshot 2022-07-28 at 14 52 47](https://user-images.githubusercontent.com/9938773/181522352-4f651d15-786c-44a4-93f2-4387c20c3ef8.png)

https://user-images.githubusercontent.com/9938773/181522787-546b5d8f-6f41-4067-8072-1a02d11ba01e.mov

2022-07-29 08:22 UTC, blurbyte requested changes

2022-07-29 08:22 UTC, blurbyte commented on doc-site/pages/components/button.mdx
> +<Example title="Is Loading" path="button/is-loading">
I think it shouldn't be standalone example but part of 'States'.

2022-07-29 08:22 UTC, blurbyte commented on src/button/__tests__/button.spec.tsx
> +  it('renders loader with isloading prop', () => {
Should be `isLoading`

2022-07-29 08:22 UTC, blurbyte commented on src/button/button-internal.tsx
> +      {...(isLoading ? { disabled: true } : null)}
Maybe `{...(isLoading && { disabled: true }}`?

2022-07-29 08:27 UTC, blurbyte requested changes
Looks nice!

A few things to update:
1. When it's icon-only button (some icon provided via `icon` prop) it should be square. if  I think removing paddings on sides and setting width to proper `sizing` depending on button size should do the trick.
2. Tbh I think 'Cannot be provided alongside the iconLeft property' is unnecessarily restrictive - just replace the content of the button when it's loading whether icon was provided or not. Provided icons shouldn't be displayed when loading. It's similar for Input, when you specify `type=search` it 'replaces' leftIcon with looking glass.
3. Something we might do in future, not necessarily now: I think it might be worth 'saving' the width of the button before loading so it won't change the size when loading is triggered. It's pretty annoying when buttons change their sizes depending on state.

2022-07-29 14:22 UTC, lensbart commented
Two minor typographic remarks:
* No space between ellipsis and preceding word
* Use the proper character `…` instead of three dots `...`

2022-08-03 12:48 UTC, blurbyte requested changes
I think that, at least for now, we don't really need `loadingLabel` - it might lead to unnecessary inconsistencies. Just hardcoded 'Loading...' string should be enough for now. Not really sure why someone would want it customized.

It's kind of good for accessibility to always show this loading label. Screen reader announces it properly as well.
For icon-only button `aria-label` should be updated to `aria-label={`${previous-aria-label} Loading`}`.

I think it might be good idea to make handling of loading a bit more clearer internally, so instead of hiding everything with CSS applied to parent, just render it conditionally and apply styles explicitly.

Also investigated a bit issue with loader SVG (it was driving me crazy 😜 ) - it seems adding some negative percentages to polygon mask in `loaderStartMask`, and `loaderEndMask` fixed it for me. Not sure if it won't break anything else.

Not entirely sure if it's me but animation seems super slow. For regular `Loader` it takes 5 seconds to complete and here it's like 10 or so.

2022-08-03 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
> +      {...(isLoading && { disabled: true })}
We will need to handle `aria-label` here to so the 'Loading' text would be appended to original one, while loading.

2022-08-03 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
> +          {iconLeft && !isLoading && renderIcon(iconLeft)}
It could be good idea to create `renderLeftIcon` helper and just based on scenario render either icon / loader / nothing in this slot.

2022-08-03 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
>            {iconRight && renderIcon(iconRight)}
Could be rendered conditionally `!isLoading && iconRight && renderIcon(iconRight)`, it will make it clearer what is happening rather than applying CSS style which is coming from parent.

2022-08-03 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
>                css={innerContentStyle({
Here I would add `isLoading` option and apply those height / width styles based on it.

2022-08-03 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
> +          {loadingLabel && <span>{loadingLabel}</span>}
For now (unless someones complain) I would just hardcode 'Loading...' label. Could use exact the same styling as for `innerContentStyle`, or just add padding to the left to compensate for loader (which is technically `iconLeft`) which will always be there.

2022-08-03 12:48 UTC, blurbyte commented on src/loader/keyframes.ts
> +    clip-path: polygon(0% -5%, 0% 178%, 188% 106%, 178% 69%);
Changing the first percentage value from 0% to -10% for all those mask styles fixed for me this weird 'cut edge' issue:

Before
<img width="101" alt="Screenshot 2022-08-03 at 13 52 58" src="https://user-images.githubusercontent.com/20565536/182611294-8c86eb3d-3677-4457-87b6-e77d9cfd3df0.png">
After
<img width="99" alt="Screenshot 2022-08-03 at 13 52 44" src="https://user-images.githubusercontent.com/20565536/182611329-55dde35a-206f-4c71-bb47-e40ddf9c8207.png">

2022-08-03 15:02 UTC, ixTec commented on src/button/button-internal.tsx
>            {iconRight && renderIcon(iconRight)}
We can't conditionally render any of the original content if we want the width to be maintained when in loading state. We instead have to hide it via opacity

2022-08-03 15:02 UTC, ixTec commented on src/button/button-internal.tsx
> +          {loadingLabel && <span>{loadingLabel}</span>}
Regarding loadingLabel, Petra wanted it customisable which is why I added it as an optional prop. I think we have an issue by showing a default label because if the original content is short then the default loading label would make the button width grow - something we want to avoid right?

2022-08-03 15:04 UTC, ixTec commented on src/button/button-internal.tsx
>                css={innerContentStyle({
Not sure I understand this? We don't want to modify the original content at all when in loading state

2022-08-03 15:06 UTC, ixTec commented on src/button/button-internal.tsx
> +          {iconLeft && !isLoading && renderIcon(iconLeft)}
We still want an iconLeft to render even in loading view (as it takes up width within the button, but will be hidden via opacity)

2022-08-04 10:11 UTC, blurbyte commented on src/button/button-internal.tsx
>                css={innerContentStyle({
Yes, you're right. It will make it shorter if we will remove it from DOM.

2022-08-04 14:01 UTC, blurbyte requested changes
There are a few issues left to fix:

- my suggestion with conditional rendering was wrong, since components will be removed from DOM and width won't be preserved, so I guess the easiest solution would be, while loading, to wrap whole content (icons, label) with some `span` and set height and opacity to 0. So ideally button width when loading should match the width when not loading. At lest for now we don't care about case when content is shorter.
<img width="241" alt="Screenshot 2022-08-04 at 14 42 22" src="https://user-images.githubusercontent.com/20565536/182866243-78d1436e-2236-48fe-ad33-3b1d9cb114ff.png">

- there is little problem with loader, it's now slightly cut diagonally at the top

2022-08-05 09:08 UTC, ixTec commented on src/button/button-internal.tsx
> +  const { 'aria-label': ariaLabel } = restProps;
Not sure I see what the difference in this vs my current approach is?

2022-08-05 09:10 UTC, ixTec commented on src/loader/__tests__/__snapshots__/loader.spec.tsx.snap
> +      viewBox="0 0 2569 3403"
Viewbox appeared to be incorrect based on the svg paths, so I had to fix this

2022-08-05 10:56 UTC, blurbyte commented
In general we stick to either `default` or `pointer`. Other cursors are fun for sure, but feel rather cheap, and so 2000. Not sure we need more cues here - there is loader and huge loading label. I can ask designers about their opinion next week.

2022-08-05 13:49 UTC, blurbyte requested changes
We are really close, there is still one issue:

<img width="255" alt="Screenshot 2022-08-05 at 15 34 15" src="https://user-images.githubusercontent.com/20565536/183090386-e559a717-3569-41b6-8223-cc889a18fbec.png">

Because when loading `flex-direction` is changed elements are stacked vertically under rather next to each other, the width is not preserved. I think we have 2 possible solutions here: either add wrapper for before-loading content or position loader content absolutely in the center of the button.

Besides that everything looks good.

2022-08-05 13:49 UTC, blurbyte commented on src/menu/button.tsx
> +      ref={(node: HTMLButtonElement) => (listRef.current[index] = node)}
Good catch 👍

2022-08-05 13:49 UTC, blurbyte commented on src/button/button-internal.tsx
> +        <div css={loaderWrapperStyle({ size, hasLoadingLabel: !icon })}>
I think it may be good idea to create separate internal component out of it.

2022-08-05 13:49 UTC, blurbyte commented on src/button/button-internal.tsx
> +  loadingLabel?: React.ReactNode;
We don't need it anymore.

2022-08-05 14:50 UTC, blurbyte requested changes

2022-08-05 14:50 UTC, blurbyte commented on src/button/button-internal.tsx
> +          {iconLeft && !isLoading && renderIcon(iconLeft)}
I was wrong with this one. In current setup, we shouldn't render it conditionally. `iconLeft && !isLoading && renderIcon(iconLeft)` is fine here.

2022-08-08 12:46 UTC, blurbyte requested changes
Looks great, just a few minor tweaks. Really like usage of `gap` in content wrapper. Makes things much cleaner.

2022-08-08 12:46 UTC, blurbyte commented on src/button/loader.tsx
> +    <div css={loaderWrapperStyle({ size, hasLoadingLabel: !hasIcon })}>
Ideally we should use `<span>` here since technically it's more semantically correct to use it within in button element.

2022-08-08 12:46 UTC, blurbyte commented on src/button/loader.tsx
> +  hasIcon: boolean;
I would change it to `isIconOnly`. I think it better describes what's the purpose of it.

2022-08-08 12:46 UTC, blurbyte commented on src/button/button-internal.tsx
> +        <span
So much simpler, thanks to `gap` 👏 .

2022-08-08 12:46 UTC, blurbyte commented on src/button/button-internal.tsx
> +            size,
I would add `isLoading` here instead of using `& > *:not(div)` in styles.

2022-08-08 12:46 UTC, blurbyte commented on src/button/button-internal.tsx
> +import ButtonLoader from './loader';
Probably can call it just `Loader` since there is no clash with our asset.

2022-08-08 12:46 UTC, blurbyte commented on src/button/styles.ts
> +    flex-direction: ${isLoading ? 'column' : 'row'};
Is it still even needed? I guess `column` should handle both.

2022-08-08 12:48 UTC, blurbyte requested changes

2022-08-08 12:48 UTC, blurbyte commented on src/button/button-internal.tsx
> +        <ButtonLoader size={size} variant={variant} inverted hasIcon={!!icon} />
When there are a lot of props with same names we can use `{...{ size, variant, inverted, isIconOnly: !!icon }}`.

2022-08-08 12:57 UTC, ixTec commented on src/button/button-internal.tsx
> +import ButtonLoader from './loader';
Keeping it as `ButtonLoader` to save us having to use an alias within the button loader component. I don't think it makes any difference in this case and helps avoid us accidentally importing it when using loader internally 😄

2022-08-08 13:02 UTC, ixTec commented on src/button/button-internal.tsx
> +        <ButtonLoader size={size} variant={variant} inverted hasIcon={!!icon} />
Good idea, cheers!

2022-08-08 13:06 UTC, ixTec commented on src/button/button-internal.tsx
> +            size,
Leaving as is, from our discussion

2022-08-08 13:10 UTC, ixTec commented on src/button/styles.ts
> +    flex-direction: ${isLoading ? 'column' : 'row'};
Good catch, `column` should now work for both as we've wrapped the content

2022-08-08 14:04 UTC, blurbyte approved these changes
Looks great! Let's merge 🚀.

2022-08-08 14:31 UTC, merged