[WF-636] Basic Card component
datacamp/waffles pull request #79
Opened 2022-08-15 12:30 UTC by blurbyte

# Basic Card component

## [WF-\*](https://datacamp.atlassian.net/browse/WF-636)

## Changes

### 🚀 Major Changes

- Created new `Card` component. Pretty much what Old Waffles offered but with simplified API (no one was using elevations).
  - Can act as any element, and in case interactive ones focus state is supported.
  - Decorators at the top of card can be added via `headstone` slot.
  - Mouse over indicator can be disabled with `disableHover`.

### 🔧 Minor Changes

- Added `Multidoc` icon
- Removed thin drop shadow in `Menu` and `Toast` in favor of border to match `Card` style

## Screenshot(s):
<img width="815" alt="Screenshot 2022-08-15 at 14 21 46" src="https://user-images.githubusercontent.com/20565536/184635225-945f029b-c2a0-4bed-a454-7f31f89bf13c.png">

2022-08-16 14:53 UTC, ixTec commented on doc-site/examples/card/with-headstone.tsx
> +          padding: ${tokens.spacing.medium};
Not sure we need the padding on a parent element instead of the Card itself?

2022-08-16 15:05 UTC, ixTec commented on src/card/__tests__/card.e2e.ts
> +describe('Card', () => {
Let's add a story for a card with the hover effect disabled

2022-08-16 15:26 UTC, ixTec requested changes
Few comments and changes requested inline, along with the following:

- I think sticking to a boolean-based prop for the hover effect is best, although I think `disableHoverEffect` would be a clearer name 
- For all our examples, we include some padding. It would be worth adding some padding to the `Card` component by default, which can be overwritten by the consumer if needed. I can't think of many helpful cases where we wouldn't want at least _some_ padding originally.
- Should we update components such as `Notification` / `Toast` to use this new `Card` internally? Perhaps even `Dialog`, `Drawer` etc could benefit from a stylised `Card` too?
- Are we offering an `inverted` variant to begin with too? Or as a future improvement to the card

2022-08-16 15:26 UTC, ixTec commented on src/card/__tests__/card.spec.tsx
> +      <Card data-testid="taylors-card">
What's the usefulness of this test? Just seems to be testing adding an additional custom prop to the element? (testing `restProps`?)

2022-08-16 15:26 UTC, ixTec commented on src/card/__tests__/card.spec.tsx
> +describe('Card', () => {
Let's add a test for with the hover effect disabled

2022-08-16 15:26 UTC, ixTec commented on src/card/card-internal.tsx
> +  /* Disables mouse over visual indicator. */
Would change this to "Disables `onHover` shadow effect"

2022-08-16 15:26 UTC, ixTec commented on src/card/card-internal.tsx
> +  /* Content to show sticking out the top of the card, e.g. can be used for technologies. Could be [Avatar](/components/avatar) from Waffles (use default `medium` size) or a custom component. */
Change to "Content positioned along the top of the card. Could be [Avatar](/components/avatar) from Waffles (use default `medium` size) or a custom component".

I think the documentation examples show the technology use case well enough

2022-08-16 15:26 UTC, ixTec commented on src/card/styles.ts
> +      padding-top: 20px;
Linking back to what I mentioned around default padding being built into the card, we will need to accommodate the header too

2022-08-17 08:06 UTC, blurbyte commented on doc-site/examples/card/with-headstone.tsx
> +          padding: ${tokens.spacing.medium};
Yes, otherwise headstone will be misaligned. Alternatively it's possible to set 28px top padding on the card itself, but I think solution with wrapper is a bit cleaner.

2022-08-17 08:07 UTC, blurbyte commented on src/card/__tests__/card.e2e.ts
> +describe('Card', () => {
Cypress doesn't support CSS hover. I tried it but there is no way to trigger it.

2022-08-17 08:08 UTC, blurbyte commented on src/card/__tests__/card.spec.tsx
> +      <Card data-testid="taylors-card">
It's common across across DC products to add some kind of tracking IDs to everything so yes, it's basically checks if `data-*` is passed properly.

2022-08-17 08:10 UTC, blurbyte commented on src/card/card-internal.tsx
> +  /* Disables mouse over visual indicator. */
I'm wondering what will be clearer for user 'on hover' or 'mouse over', considering nowadays many front-end devs are not THAT familiar with CSS.

2022-08-17 08:13 UTC, blurbyte commented on src/card/styles.ts
> +      padding-top: 20px;
Tbh at first I had default padding baked in, but turns out most real implementations in apps are adding some kind of horizontal separator or image or w/e, so they would have to remove padding anyway. Overall I don't like it as it is but it 1:1 to what `Card` from Old Waffles is, so at least migration will be easier.

2022-08-17 08:32 UTC, blurbyte commented
For now I just basically ported Old Waffles card without `elevation` API, so migration should be easier. Ideally in future we will have more advanced version of the component which will handle at least most common use cases. Some of my thoughts regarding feedback:

-`disableHover` should be fine, especially with an example
- in reality most of cards in apps have some custom content and paddings would have to be zeroed-out anyway
- in terms of updating other components I think we should wait for final version of the card, for now it's basically just 2 tokens
- `inverted` sounds like good idea for future update

2022-08-17 09:03 UTC, ixTec reviewed
I still think `disableHoverEffect` is a clearer name for the prop as I could see confusion in thinking it disables the hover event / interaction for the component - perhaps we can ask some other developers on this one?

Regarding the padding, it's probably worth still adding some default padding (factoring in the top padding for the headstone too). Something like small or medium spacing would likely be enough. If someone wants something incredibly different they can wrap their content and pad the wrapper or overwrite the card component, but ultimately I think trying to provide a generic standard for card use would be useful.

2022-08-17 09:03 UTC, ixTec commented on src/card/card-internal.tsx
> +  /* Disables mouse over visual indicator. */
I'd stick with `on hover` for this case imo

2022-08-17 11:41 UTC, ixTec commented
I'm noticing some odd flickering on the box shadow when it appears on hover (kinda hard to see on the recording). Is this the intentional look or?


https://user-images.githubusercontent.com/9938773/185109902-0f8b90c6-4a63-482e-885e-13bc1812f240.mov

2022-08-17 13:34 UTC, ixTec commented
Haven't been able to find some cubic values that help the above issue, so I'm just going to approve this. If anyone else raises an issue with it after release, we'll know it's not just my monitors / eyes 😄

2022-08-17 13:34 UTC, ixTec approved these changes

2022-08-17 15:10 UTC, merged