[WF-637] Code & Link improvements
datacamp/waffles pull request #87
Opened 2022-08-24 13:58 UTC by blurbyte

# Insert Description Here

## [WF-637](https://datacamp.atlassian.net/browse/WF-637)

A little overhaul of `Code`, `CodeBlock`, and `Link` components so they behave in more consistent way (and stay in line with `Paragraph`, which is the most common use case).

## Changes

### 🚀 Major Changes

- Updated `Code` component
  - By default it inherits font size
  - Added `small` size (to match `Paragraph`
- Updated `CodeBlock` component
  - Added `small` size (to be consistent with `Code`)
- Updated `Link` component
  - By default it inherits font size (as it was)
  - Size of the icon is calculated automatically based on the font size (not sure if it's not overkill here), but of course could be set to different size if needed
  - Added sizes to match Paragraph / Code API
  - Animated underline
  - Changed display to `inline` so it wraps nicer between the lines

## Screenshot(s):
<img width="1181" alt="Screenshot 2022-08-24 at 15 57 26" src="https://user-images.githubusercontent.com/20565536/186437523-cc261e29-bc60-4c7e-bbea-47d2509eed83.png">
<img width="457" alt="Screenshot 2022-08-24 at 15 55 13" src="https://user-images.githubusercontent.com/20565536/186437574-b668599a-126b-4976-bad2-279b455634a5.png">
<img width="460" alt="Screenshot 2022-08-24 at 15 55 22" src="https://user-images.githubusercontent.com/20565536/186437603-81aadb46-cf28-4713-951b-c3a1ecf42df9.png">

2022-08-25 13:50 UTC, ixTec requested changes
Looks great, love the new addition of the `small` variants for `Code` etc. Couple of comments/thoughts.

- We should update the badge/code for our default value in the props table to use this new variant (along with making badge small now). 
- `Link` prop docs for `iconLeft` and `iconRight` should be updated to remove the suggestion to use `small` icons with smaller text - this is now the default behaviour

In terms changes to mark as **🚨 Breaking Changes**, here are my thoughts:
- `Code` component now inherits  a `font-size: 86%` from parent by default (
    - Was `medium` `size` beforehand
- `Icon`s within `Link` components will now have their `size` set automatically based on `font-size`. This can be overwritten by manually setting a `size`.
- `Link` now has `display: inline` for it's default styling, so it wraps better between lines

2022-08-25 13:50 UTC, ixTec commented on doc-site/pages/components/link.mdx
> +  description="In general just let the link inherit font size from the surrounding text."
I am not sure these kind of comments need to be within a `Notification` - probably best to just have it as a paragraph / bullet point under "Usage Guidelines"

2022-08-25 13:50 UTC, ixTec commented on src/code/__tests__/code-explicit-size.story.tsx
> +        <Code size="medium">inline code fragment of the small size</Code> enim
"of the  _medium_ size"

2022-08-25 13:50 UTC, ixTec commented on src/code/__tests__/code-explicit-size.story.tsx
> +        <Code size="large">inline code fragment of the small size</Code> enim ad
"of the _large_ size"

2022-08-25 13:50 UTC, ixTec commented on src/code/styles.ts
> +  line-height: inherit;
We probably only want to inherit `line-height` when the `size` = `inherit` right? Just in case there's anything wild being set on the parent

2022-08-25 13:50 UTC, ixTec commented on doc-site/examples/code-block/sizes.tsx
> +      <CodeBlock size="small">{`pyftsubset JetBrainsMono.ttf
We probably need to add `flex-wrap` on a parent or something for the codeblock examples as they currently cause the container to be wider than it should (causing overflow on smaller screen widths)

2022-08-25 13:50 UTC, ixTec commented on doc-site/examples/code/basic-usage.tsx
> +      <Paragraph size="small">
I don't think we need `small` and `large` variants within our `basic-usage` example - just the default behaviour should be enough

2022-08-26 07:23 UTC, blurbyte commented on doc-site/pages/components/link.mdx
> +  description="In general just let the link inherit font size from the surrounding text."
Yeah, probably overkill here. Not even sure if it should be mentioned really :)

2022-08-26 07:25 UTC, blurbyte commented on src/code/styles.ts
> +  line-height: inherit;
Makes sense.

2022-08-26 07:26 UTC, blurbyte commented on doc-site/examples/code/basic-usage.tsx
> +      <Paragraph size="small">
Agree, especially now when they inherit font size doesn't make sense to show all sizes.

2022-08-30 10:46 UTC, ixTec requested changes
very nearly there!

I would also add a new "Basic Usage" example for `Code Block` now too.

2022-08-31 11:00 UTC, ixTec approved these changes
LGTM :)

2022-08-31 11:55 UTC, merged