[WF-647] Add new `useTitleCase` hook
datacamp/waffles pull request #90
Opened 2022-08-31 09:09 UTC by ixTec

# Add new `useTitleCase` hook

## [WF-647](https://datacamp.atlassian.net/browse/WF-*)

## Changes

### 🚨 Breaking Changes

- `Button` now has the `useTitleCase` utility applied to the child content by default, if it's of type string.
    - This can be disabled via the new `disableTitleCase` prop on `Button` (should be used sparingly).

### 🚀 Major Changes

- Added new `useTitleCase` hook for applying title casing to provided content
    - Used internally by `Button`

### 🔧 Minor Changes

- Fixed missing `hideLabel` entry in `Progress` component docs prop table

### ❓ Misc Changes

- Docs table of contents items utilise `disableTitleCase` prop, to solve issues with headings for hooks (e.g. useId)

## Screenshot(s):
![Screenshot 2022-08-31 at 10 08 42](https://user-images.githubusercontent.com/9938773/187642453-26de35a3-ec2c-4d6d-9072-2e97a65f0e4d.png)

2022-08-31 09:13 UTC, ixTec commented
@blurbyte 

Few comments on this initially for you - 

The hook does not work in the following cases:

- Words wrapped in brackets (e.g. "this is a (fun) button" becomes "This is a (fun) Button" (same applies for punctuation separating words (it works from spaces).
- Camel-cased words (obviously). I've added the `disableTitleCase` prop to button to get around this for things such as our table of contents items on docs.
- It will not maintain existing capitalisation. E.g. text with "click HERE for fun" will become "Click Here for Fun" etc.

We can solve these by adding further checks / configuration for the hook, but I wonder if it goes too far.

2022-08-31 10:29 UTC, blurbyte requested changes
The more I think about it the more I am convinced it should be just helper function rather than hook.

Also I think we should change all our headings to _Sentence case_ since new guidelines were officially established on Slack :)

2022-08-31 10:29 UTC, blurbyte commented on src/dialog/__tests__/__snapshots__/dialog.spec.tsx.snap
> +         Dismiss
Looks like a space is added here which is kind of suspicious.

2022-09-01 11:00 UTC, blurbyte requested changes
Looks great overall. Thanks for doing boring job and updating all headings.
I think only in global README it hasn't been updated yet.

2022-09-01 11:04 UTC, blurbyte requested changes

2022-09-01 11:04 UTC, blurbyte commented on doc-site/pages/components/helpers.mdx
> +Converts the provided string to match the required title case. Waffles [Button](/components/button) uses this for provided string content by default.
Maybe `Converts provided text to _Title Case_. ...`

2022-09-01 11:04 UTC, blurbyte commented on src/helpers/set-title-case.ts
> +function setTitleCase(content: string) {
Missing some JSDocs here similar to other helpers.

2022-09-01 12:40 UTC, ixTec commented on src/button/button-internal.tsx
> +  /* Disables the default title casing for type `string` children. Use only in rare situations. */
Good idea :)

2022-09-01 13:59 UTC, blurbyte approved these changes
Looks really nice, let's merge.

2022-09-01 14:30 UTC, merged