[WF-566] Slider component
datacamp/waffles pull request #92
Opened 2022-09-02 08:58 UTC by blurbyte

# New Slider component

## [WF-566](https://datacamp.atlassian.net/browse/WF-566)

## Changes

Implemented new `Slider` component. Under the hood it uses `react-range` lib (only 5KB gzipped), some APIs and internal implementations are dictated by this lib.

### 🚀 Major Changes

- Added `Slider` component:
  - it's controlled component so state is handled in the parent component
  - accepts array as a `value`: when one number is passed (e.g. `[10]`) single thumb / handle is shown, but for two numbers (e.g. `[10, 30]`) it shows range between two thumbs
  - min, max, and step (fraction could be set too) are configurable
  - all labels could be hidden with `hideLabels`
  - inputs to enter values directly could be displayed with `showInputs` (not affected by `hideLabels`), they are shown instead of current value
  - inverted and disabled styles are available
  - labels could be formatted with `formatLabel`, when e.g. currency must be selected
 
### ❓ Misc Changes

- Added `react-range` dependency to handle complex slider logic
- Bumped `floating-ui` version

## Screenshot(s):
<img width="1345" alt="Screenshot 2022-09-02 at 10 39 23" src="https://user-images.githubusercontent.com/20565536/188103733-195b0332-9a38-4876-9e22-0844fcf7083c.png">
<img width="1343" alt="Screenshot 2022-09-02 at 10 43 15" src="https://user-images.githubusercontent.com/20565536/188103759-47dc79c2-5590-4e09-aaed-3a760d6d3ac9.png">
<img width="1344" alt="Screenshot 2022-09-02 at 10 43 35" src="https://user-images.githubusercontent.com/20565536/188103780-7235d341-f6e6-4f53-b26d-643a3a70060d.png">

2022-09-02 15:02 UTC, ixTec requested changes
Honestly looks great to the eyes, such a clean and easy user interaction!

Added a couple of comments / thoughts

- Inputs should likely just have a `min-width` instead of `width`, because there's some overflow issues with large number lengths 
    - Content should also probably be centre aligned?
    - ![Screenshot 2022-09-02 at 14 29 30](https://user-images.githubusercontent.com/9938773/188156474-3bc28c10-141b-4280-b794-ffaf205a000d.png)
- I am _really_ not a fan of the term `Thumb`, and although I can see it's the name used by `react-range`, I would choose an alternative for our prop/naming for clarity, perhaps `Handle` or `Slider` itself, with the actual waffles component being renamed to `Interactive Range` or `Range Slider`. Something to discuss during work week perhaps

2022-09-05 09:47 UTC, blurbyte commented
Agree with `Thumb` - personally not a big fan of it too, but decided to it because `react-range` using it, and Material Design guidelines probably popularized this term. Will change it to `Handle`.
For inputs I think their widths will have to be calculated up front based on max / step values. It's super awkward if inputs change their size when typing (this would happen with `min-width`. Since values are numbers only it should be rather easy to implement (just digits count multiplied by some hardcoded value). I guess we shouldn't rally care about incorrect values here.

2022-09-05 09:53 UTC, blurbyte commented on src/slider/inputs.tsx
> +    value: string | number,
Can't do that because, e.g. case when user want to type decimal `10.` it would have to be parsed to `10` immediately so `.` would be gone making whole experience very awkward.

2022-09-05 09:57 UTC, blurbyte commented on src/slider/slider-context.tsx
> +  if (context === undefined) {
I guess it doesn't really hurt do have it there - could be easy to forget in future if we will decide to expose this hook.

2022-09-05 11:04 UTC, blurbyte commented on src/slider/inputs.tsx
> +    setHasError(initalError(isSingleInput));
Time to invest in some spell checker plugin for VSCode :)

2022-09-05 11:08 UTC, blurbyte commented on src/slider/limit-labels.tsx
> +function LimitLabels({ formatLabel }: LimitLabelsProps) {
Was my initial thought for its name too, but was worried it would imply it has something to do with selecting custom range.

2022-09-05 11:13 UTC, blurbyte commented on src/slider/slider.tsx
> +        <Range
Good idea 👍

2022-09-05 11:45 UTC, blurbyte commented on src/slider/styles.ts
> +    margin-left: -${THUMB_DOT_RADIUS / 2}px;
I prefer to reserve `calc` for calculating dynamic values, instead of something I know during design.

2022-09-05 12:50 UTC, blurbyte commented on src/slider/slider.tsx
> +  if (value.length > 2 || value.length === 0) {
Yeah, but it's kind of hard to make it compatible with `react-range` and `onChange` handler without some ugly TS casts. So not sure if it's worth the trouble.
Also not 100% convinced if it's good idea to offer single number or array depending on type of Slider you want to have. Especially for `onChange` you will have to remember to use the proper one again.

2022-09-12 10:14 UTC, ixTec commented on src/slider/inputs.tsx
> +    value: string | number,
interesting issue - I hadn't considered this!

2022-09-14 09:02 UTC, ixTec requested changes
Looks like there's a handful of new issues and I've added some additional comments too:

- Input fields should probably show numbers to the the full decimal places, to avoid jumping between character lengths
- The error state still isn't very clear imo - perhaps we need design consultation because when an input is invalid, it gives no reason for why, including no indication for screen readers
- Story file names can probably be a bit more detailed e.g. `slider-with-inputs` instead of 'slider-input`

2022-09-14 09:02 UTC, ixTec commented on src/slider/slider.tsx
> +  onChange: (value: number[]) => void;
Really not sure we want onChange and onChangeEnd still - they're used for similar purposes internally, except within the react-range component. We likely just care to expose one of the two as a prop

2022-09-14 14:51 UTC, blurbyte commented on src/slider/slider.tsx
> +  onChange: (value: number[]) => void;
I think we need both:
- onChange is used to set a value (and is constantly updating when user moves a handle)
- onChangeEnd is used to retrieve the last value after handle stops moving
So the first one is not really feasible if you want for example send an XHR request with a slider value.

2022-09-19 13:45 UTC, blurbyte commented on src/slider/slider.tsx
> +  onChange: (value: number[]) => void;
After discussion: we decided to remove this onChangeEnd callback.

2022-09-20 10:36 UTC, blurbyte commented on src/slider/slider.tsx
> +  function handleSecondInputChange(event: React.ChangeEvent<HTMLInputElement>) {
Moved them to `Input` component, should be easier to digest.

2022-09-20 10:37 UTC, blurbyte commented on src/slider/slider.tsx
> +  // Separate each input handler for readability
Added some additional comments.

2022-09-20 10:37 UTC, blurbyte commented on src/slider/value-labels.tsx
> +  const isSingleValue = value.length === 1;
I would prefer to leave it at is is to be super explicit.

2022-09-20 10:39 UTC, blurbyte commented
A few improvements:
- added input error messages below Slider, they work nicely with screen reader
- moved each input handler from Slider to Inputs
- fixed an issue with an input when it was impossible to type value like `10.00001`

2022-09-20 14:39 UTC, ixTec requested changes
I would say it's almost there!

Couple of minor comments in the code and the one below, before we're good to merge:

- Regarding the error messages for our inputs, we can likely set these strings to CONST's or util literals so we can just populate whether it's first/second input. this would remove the current duplication we have

We can definitely make some further improvements later on as a separate task :)

2022-09-20 14:39 UTC, ixTec commented on src/slider/inputs.tsx
> +  // Short overview of how each handler works:
We could do with some more punctuation in these comments, just to help readability etc. See suggestion below:

``` 
  // 1. Only numeric values are allowed
  // 2. When user starts typing, any error for the Input is cleared
  // 3. For better UX, some additional checks are performed before setting final value on Slider. So sometimes Slider and Input values are out of sync, e.g. value ending with dot
  // 4. If Input value passes checks, parsed value is set on slider
  // 5. Otherwise an appropriate error is displayed
  ```

2022-09-20 14:39 UTC, ixTec commented on src/slider/inputs.tsx
> +        setError(['First input value is out of allowed range.', error[1]]);
is _outside_ of

2022-09-20 14:39 UTC, ixTec commented on src/slider/inputs.tsx
> +        setError(['First input value is not overlapping with step.', error[1]]);
Maybe `First input value is a valid step increment` - if I'm understanding this error correctly

2022-09-20 14:39 UTC, ixTec commented on src/slider/inputs.tsx
> +          'Second input value is not overlapping with step.',
Maybe `Second input value is a valid step increment` - if I'm understanding this error correctly

2022-09-20 14:39 UTC, ixTec commented on src/slider/inputs.tsx
> +        setError([error[0], 'Second input value is out of allowed range.']);
is outside of

2022-09-20 14:39 UTC, ixTec commented on src/slider/slider.tsx
> +  /* Current slider value. Array of values. For single handle provide single value e.g. `[20]`, and for range provide two values, e.g. `[20, 50]`. */
Maybe reword as "Current slider value(s) as an array. For a single-value slider, provide a single value array e.g. `[20]`, and for a range slider provide two values, e.g. `[20, 50]`".

2022-09-20 14:39 UTC, ixTec commented on src/slider/slider.tsx
> +  /* The minimum allowed value of the slider. Can be decimal or negative. */
"Can be _a_ decimal or..."

2022-09-20 14:39 UTC, ixTec commented on src/slider/slider.tsx
> +  /* The maximum allowed value of the slider. Can be decimal or negative. */
"Can be _a_ decimal or..."

2022-09-20 14:39 UTC, ixTec commented on src/slider/slider.tsx
> +  /* The minimal distance between values. Can be decimal. */
"Can be _a_ decimal."

2022-09-20 14:39 UTC, ixTec commented on src/slider/utils.ts
> +// Check if value could be safely set on slider
"..._can_ be..."

2022-09-21 10:01 UTC, ixTec approved these changes
Let's mergeeee 🥇

2022-09-21 10:06 UTC, merged