[WF-652] Improve icon-only Button and docs
datacamp/waffles pull request #99
Opened 2022-09-28 09:45 UTC by ixTec

# Improve icon-only Button and docs

## [WF-652](https://datacamp.atlassian.net/browse/WF-652)

## Changes

### 🚨 Breaking Changes

- Throw error when incorrect syntax for `Button` is used with empty string children (`<Button ...>{''}</Button>` instead of `<Button ... />`
    - Technically a breaking change because this _will_ throw an error for all incorrect solutions

### 🔧 Minor Changes

- Updated prop documentation for `children` for `Button`

### ❓ Misc Changes

- Updated best practices for `Button`
- General grammar fixes for `Button` docs

2022-09-28 12:04 UTC, blurbyte requested changes
A lot of nice updates. Any reason for capitalising 'button'?

2022-09-28 12:04 UTC, blurbyte commented on src/button/button-internal.tsx
> +  // Handle cases where incorrect syntax is used
I would make it a bit more precise 'When empty string is passed incorrectly'

2022-09-28 12:04 UTC, blurbyte commented on src/button/button-internal.tsx
> +      'Button cannot have an empty string for children. Use `<Button ... />` syntax instead.',
Really like this error. Maybe would make sense to mention `aria-label` in `<Button ... />`?

2022-09-28 12:04 UTC, blurbyte commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
Not really a fan of capitalising Button on this page. Any particular reason for doing so?

2022-09-28 14:02 UTC, ixTec commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
Since it's the name of our component, it should be capitalised. I've updated this throughout the Button docs where found

2022-09-28 14:02 UTC, ixTec commented on src/button/button-internal.tsx
> +      'Button cannot have an empty string for children. Use `<Button ... />` syntax instead.',
Good idea!

2022-09-29 08:36 UTC, blurbyte commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
I still think it makes more sense to not capitalise it:
- we want our users to treat our components as a natural go-to elements, so whenever they want to place a button on the page they use `Button`, and I lower-case naming helps with assimilating this concept
- if we want to capitalise it, probably we should also render it as `Code`, which makes overall doc page too busy imho

2022-09-29 08:47 UTC, ixTec commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
Hmm I think we have to be careful here when referring to one of _our_ components and a generic / native element. An example of this is icon, where we use it to primarily refer to our Icon component, not a custom SVG icon etc. Similar to our Input component, we don't want to confuse them with native HTML inputs. `Input` !== `input` etc.

I think we get away with not wrapping it as `Code`, and instead just linking off to the correct documentation page when not already on that page. E.g. references of `Icon` link off to Icon docs

2022-09-30 07:05 UTC, blurbyte commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
For general guidelines I think speaking in more generic terms is better, so when we want the user to use that particular component (capitalised + link / code), like `Icon` or `Link` in this case, it will stand out more.

2022-09-30 13:33 UTC, ixTec commented on doc-site/pages/components/button.mdx
> +<Layout title="Button" description="A Button triggers an event or action. It lets users know what will happen next. Use actionable copy, don’t be vague.">
Updated casing throughout button docs as discussed earlier today

2022-10-03 08:52 UTC, blurbyte requested changes
A few minor fixes, and we are good to go.

2022-10-03 08:52 UTC, blurbyte commented on doc-site/pages/components/button.mdx
>      - use `upgrade` button for actions other than upgrading to different plan
Should be capitalized here.

2022-10-03 08:52 UTC, blurbyte commented on doc-site/pages/components/button.mdx
> +    - for an icon-only button, provide `aria-label` for both `Button` and [Icon](/components/icon) components
Probably we can omit wrapping Button with code here (for BestPractices and PropsTable I think we can skip it).

2022-10-03 08:52 UTC, blurbyte commented on src/button/button-internal.tsx
> +  /* The content inside the button. Most of the time should be a plain text. Should never be an empty string. */
I think it should be capitalized here(?)

2022-10-03 08:52 UTC, blurbyte commented on src/button/button-internal.tsx
>    /* Allows the button to grow to the width of its container. */
Should be capitalized here.

2022-10-03 10:14 UTC, blurbyte approved these changes
Looks nice 🚀

2022-10-03 10:29 UTC, merged